//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividad_mantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actividad_mantenimiento()
        {
            this.detalle_plan_mantenimiento = new HashSet<detalle_plan_mantenimiento>();
            this.actividad_mantenimiento_especialidad = new HashSet<actividad_mantenimiento_especialidad>();
            this.detalle_orden_trabajo_mantenimiento = new HashSet<detalle_orden_trabajo_mantenimiento>();
            this.detalle_consumo_agil_mantenimiento = new HashSet<detalle_consumo_agil_mantenimiento>();
            this.actividad_mantenimiento_herramienta = new HashSet<actividad_mantenimiento_herramienta>();
            this.lectura_mantenimiento = new HashSet<lectura_mantenimiento>();
            this.actividad_mantenimiento_material = new HashSet<actividad_mantenimiento_material>();
            this.detalle_presupuesto_mantenimiento = new HashSet<detalle_presupuesto_mantenimiento>();
        }
    
        public int id_actividad_mantenimiento { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_organizacion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string nombre { get; set; }
        public bool planificada { get; set; }
        public bool predeterminado { get; set; }
        public int id_tipo_actividad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_mantenimiento> detalle_plan_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividad_mantenimiento_especialidad> actividad_mantenimiento_especialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_orden_trabajo_mantenimiento> detalle_orden_trabajo_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_consumo_agil_mantenimiento> detalle_consumo_agil_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividad_mantenimiento_herramienta> actividad_mantenimiento_herramienta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lectura_mantenimiento> lectura_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividad_mantenimiento_material> actividad_mantenimiento_material { get; set; }
        public virtual tipo_actividad tipo_actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_presupuesto_mantenimiento> detalle_presupuesto_mantenimiento { get; set; }
    }
}
