//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ajuste_prefactura_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ajuste_prefactura_cliente()
        {
            this.detalle_ajuste_prefactura_cliente = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.ajuste_prefactura_cliente1 = new HashSet<ajuste_prefactura_cliente>();
        }
    
        public int id_ajuste_prefactura_cliente { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public decimal descuento { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_contabilizacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public decimal impuesto { get; set; }
        public decimal total { get; set; }
        public Nullable<int> id_ajuste_prefactura_cliente_padre { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public Nullable<int> id_prefactura_cliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajuste_prefactura_cliente> ajuste_prefactura_cliente1 { get; set; }
        public virtual ajuste_prefactura_cliente ajuste_prefactura_cliente2 { get; set; }
        public virtual prefactura_cliente prefactura_cliente { get; set; }
        public virtual asiento asiento { get; set; }
    }
}
