//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anticipo_proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public anticipo_proveedor()
        {
            this.liquidacion_anticipo_proveedor = new HashSet<liquidacion_anticipo_proveedor>();
        }
    
        public int id_anticipo_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string beneficiario { get; set; }
        public string descripcion { get; set; }
        public string descripcion_devolucion { get; set; }
        public string documento_referencia { get; set; }
        public string documento_referencia_devolucion { get; set; }
        public int estado { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_contabilizacion { get; set; }
        public Nullable<System.DateTime> fecha_devolucion { get; set; }
        public Nullable<System.DateTime> fecha_entrega_cheque { get; set; }
        public Nullable<System.DateTime> fecha_posfechado { get; set; }
        public int id_organizacion { get; set; }
        public bool indicador_cheque_entregado { get; set; }
        public bool indicador_cheque_posfechado { get; set; }
        public Nullable<bool> indicador_contabilizar { get; set; }
        public bool indicador_saldo_inicial { get; set; }
        public string nota_posfechado { get; set; }
        public string numero { get; set; }
        public string pdf { get; set; }
        public decimal saldo { get; set; }
        public string usuario_aprobacion { get; set; }
        public string usuario_entrega_cheque { get; set; }
        public decimal valor { get; set; }
        public Nullable<decimal> valor_devolucion { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public Nullable<int> id_asiento_devolucion { get; set; }
        public Nullable<int> id_cuenta_bancaria_organizacion { get; set; }
        public Nullable<int> id_cuenta_bancaria_organizacion_devolucion { get; set; }
        public Nullable<int> id_cuenta_contable_banco_pago_cash { get; set; }
        public Nullable<int> id_detalle_orden_pago_proveedor { get; set; }
        public int id_documento { get; set; }
        public Nullable<int> id_documento_devolucion { get; set; }
        public int id_empresa { get; set; }
        public Nullable<int> id_factura_proveedor_sri { get; set; }
        public Nullable<int> id_forma_pago { get; set; }
        public Nullable<int> id_forma_pago_devolucion { get; set; }
        public Nullable<int> id_factura_proveedor { get; set; }
        public Nullable<int> id_pago_cash { get; set; }
        public Nullable<int> id_pedido_proveedor { get; set; }
        public Nullable<int> id_persona_responsable { get; set; }
        public int id_sucursal { get; set; }
    
        public virtual asiento asiento { get; set; }
        public virtual factura_proveedorSRI factura_proveedorSRI { get; set; }
        public virtual pago_cash pago_cash { get; set; }
        public virtual asiento asiento1 { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual documento documento { get; set; }
        public virtual documento documento1 { get; set; }
        public virtual pedido_proveedor pedido_proveedor { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual responsable_salida_mercaderia responsable_salida_mercaderia { get; set; }
        public virtual cuenta_bancaria_organizacion cuenta_bancaria_organizacion { get; set; }
        public virtual detalle_orden_pago_proveedor detalle_orden_pago_proveedor { get; set; }
        public virtual cuenta_bancaria_organizacion cuenta_bancaria_organizacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<liquidacion_anticipo_proveedor> liquidacion_anticipo_proveedor { get; set; }
        public virtual factura_proveedor factura_proveedor { get; set; }
        public virtual forma_pago forma_pago { get; set; }
        public virtual forma_pago forma_pago1 { get; set; }
        public virtual cuenta_contable cuenta_contable { get; set; }
    }
}
