//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class as2oasis : DbContext
    {
        public as2oasis()
            : base("name=as2oasis")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GuiaUrbano> GuiaUrbano { get; set; }
        public virtual DbSet<presupuesto_cabecera> presupuesto_cabecera { get; set; }
        public virtual DbSet<presupuesto_detalle> presupuesto_detalle { get; set; }
        public virtual DbSet<Cobros_Consolidado> Cobros_Consolidado { get; set; }
        public virtual DbSet<Ventas_Consolidado> Ventas_Consolidado { get; set; }
    
        public virtual ObjectResult<Presupuesto_Result> Presupuesto(string empresa, string sucursal, Nullable<System.DateTime> fecha_desde, Nullable<System.DateTime> fecha_hasta, string tipoCliente)
        {
            var empresaParameter = empresa != null ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(string));
    
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("sucursal", sucursal) :
                new ObjectParameter("sucursal", typeof(string));
    
            var fecha_desdeParameter = fecha_desde.HasValue ?
                new ObjectParameter("fecha_desde", fecha_desde) :
                new ObjectParameter("fecha_desde", typeof(System.DateTime));
    
            var fecha_hastaParameter = fecha_hasta.HasValue ?
                new ObjectParameter("fecha_hasta", fecha_hasta) :
                new ObjectParameter("fecha_hasta", typeof(System.DateTime));
    
            var tipoClienteParameter = tipoCliente != null ?
                new ObjectParameter("tipoCliente", tipoCliente) :
                new ObjectParameter("tipoCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Presupuesto_Result>("Presupuesto", empresaParameter, sucursalParameter, fecha_desdeParameter, fecha_hastaParameter, tipoClienteParameter);
        }
    
        public virtual ObjectResult<NCPorVendedor_Result> NCPorVendedor(string empresa, string sucursal, Nullable<System.DateTime> fecha_desde, Nullable<System.DateTime> fecha_hasta, string tipoCliente, string idvendedor)
        {
            var empresaParameter = empresa != null ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(string));
    
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("sucursal", sucursal) :
                new ObjectParameter("sucursal", typeof(string));
    
            var fecha_desdeParameter = fecha_desde.HasValue ?
                new ObjectParameter("fecha_desde", fecha_desde) :
                new ObjectParameter("fecha_desde", typeof(System.DateTime));
    
            var fecha_hastaParameter = fecha_hasta.HasValue ?
                new ObjectParameter("fecha_hasta", fecha_hasta) :
                new ObjectParameter("fecha_hasta", typeof(System.DateTime));
    
            var tipoClienteParameter = tipoCliente != null ?
                new ObjectParameter("tipoCliente", tipoCliente) :
                new ObjectParameter("tipoCliente", typeof(string));
    
            var idvendedorParameter = idvendedor != null ?
                new ObjectParameter("idvendedor", idvendedor) :
                new ObjectParameter("idvendedor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NCPorVendedor_Result>("NCPorVendedor", empresaParameter, sucursalParameter, fecha_desdeParameter, fecha_hastaParameter, tipoClienteParameter, idvendedorParameter);
        }
    
        public virtual ObjectResult<VentasPorVendedor_Result> VentasPorVendedor(string empresa, string sucursal, Nullable<System.DateTime> fecha_desde, Nullable<System.DateTime> fecha_hasta, string tipoCliente, string idvendedor)
        {
            var empresaParameter = empresa != null ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(string));
    
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("sucursal", sucursal) :
                new ObjectParameter("sucursal", typeof(string));
    
            var fecha_desdeParameter = fecha_desde.HasValue ?
                new ObjectParameter("fecha_desde", fecha_desde) :
                new ObjectParameter("fecha_desde", typeof(System.DateTime));
    
            var fecha_hastaParameter = fecha_hasta.HasValue ?
                new ObjectParameter("fecha_hasta", fecha_hasta) :
                new ObjectParameter("fecha_hasta", typeof(System.DateTime));
    
            var tipoClienteParameter = tipoCliente != null ?
                new ObjectParameter("tipoCliente", tipoCliente) :
                new ObjectParameter("tipoCliente", typeof(string));
    
            var idvendedorParameter = idvendedor != null ?
                new ObjectParameter("idvendedor", idvendedor) :
                new ObjectParameter("idvendedor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VentasPorVendedor_Result>("VentasPorVendedor", empresaParameter, sucursalParameter, fecha_desdeParameter, fecha_hastaParameter, tipoClienteParameter, idvendedorParameter);
        }
    
        public virtual ObjectResult<CobrosPorVendedor_Result> CobrosPorVendedor(string empresa, string sucursal, Nullable<System.DateTime> fecha_desde, Nullable<System.DateTime> fecha_hasta, string tipoCliente, string idvendedor)
        {
            var empresaParameter = empresa != null ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(string));
    
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("sucursal", sucursal) :
                new ObjectParameter("sucursal", typeof(string));
    
            var fecha_desdeParameter = fecha_desde.HasValue ?
                new ObjectParameter("fecha_desde", fecha_desde) :
                new ObjectParameter("fecha_desde", typeof(System.DateTime));
    
            var fecha_hastaParameter = fecha_hasta.HasValue ?
                new ObjectParameter("fecha_hasta", fecha_hasta) :
                new ObjectParameter("fecha_hasta", typeof(System.DateTime));
    
            var tipoClienteParameter = tipoCliente != null ?
                new ObjectParameter("tipoCliente", tipoCliente) :
                new ObjectParameter("tipoCliente", typeof(string));
    
            var idvendedorParameter = idvendedor != null ?
                new ObjectParameter("idvendedor", idvendedor) :
                new ObjectParameter("idvendedor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CobrosPorVendedor_Result>("CobrosPorVendedor", empresaParameter, sucursalParameter, fecha_desdeParameter, fecha_hastaParameter, tipoClienteParameter, idvendedorParameter);
        }
    }
}
