//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion_atributo
    {
        public int id_asignacion_atributo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public int id_organizacion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public int orden { get; set; }
        public int id_atributo { get; set; }
        public int id_conjunto_atributo { get; set; }
    
        public virtual conjunto_atributo conjunto_atributo { get; set; }
        public virtual atributo atributo { get; set; }
    }
}
