//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asistencia()
        {
            this.asistencia1 = new HashSet<asistencia>();
        }
    
        public int id_asistencia { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> dia_mes { get; set; }
        public Nullable<System.TimeSpan> entrada { get; set; }
        public Nullable<System.TimeSpan> entrada_receso { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_filtro { get; set; }
        public Nullable<bool> horario_beneficio1 { get; set; }
        public Nullable<bool> horario_beneficio2 { get; set; }
        public Nullable<bool> horario_beneficio3 { get; set; }
        public Nullable<bool> horario_beneficio4 { get; set; }
        public Nullable<bool> horario_beneficio5 { get; set; }
        public Nullable<bool> horario_beneficio_aprobada1 { get; set; }
        public Nullable<bool> horario_beneficio_aprobada2 { get; set; }
        public Nullable<bool> horario_beneficio_aprobada3 { get; set; }
        public Nullable<bool> horario_beneficio_aprobada4 { get; set; }
        public Nullable<bool> horario_beneficio_aprobada5 { get; set; }
        public Nullable<decimal> horas_extras100 { get; set; }
        public Nullable<decimal> horas_extras100_aprobadas { get; set; }
        public Nullable<decimal> horas_extras100_feriado { get; set; }
        public decimal horas_extras100_feriado_aprobadas { get; set; }
        public Nullable<decimal> horas_extras25 { get; set; }
        public Nullable<decimal> horas_extras25_aprobadas { get; set; }
        public Nullable<decimal> horas_extras50 { get; set; }
        public Nullable<decimal> horas_extras50_aprobadas { get; set; }
        public Nullable<decimal> horas_falta { get; set; }
        public Nullable<decimal> horas_permiso { get; set; }
        public int horas_semana { get; set; }
        public Nullable<int> horas_subsidio { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_creada_manualmente { get; set; }
        public bool indicador_dia_complementario { get; set; }
        public Nullable<bool> indicador_dia_descanso { get; set; }
        public bool indicador_dia_festivo { get; set; }
        public bool indicador_dia_opcional { get; set; }
        public Nullable<bool> indicador_horas_adelanto_extra { get; set; }
        public Nullable<bool> indicador_modificado_manual1 { get; set; }
        public Nullable<bool> indicador_modificado_manual10 { get; set; }
        public Nullable<bool> indicador_modificado_manual11 { get; set; }
        public Nullable<bool> indicador_modificado_manual12 { get; set; }
        public Nullable<bool> indicador_modificado_manual2 { get; set; }
        public Nullable<bool> indicador_modificado_manual3 { get; set; }
        public Nullable<bool> indicador_modificado_manual4 { get; set; }
        public Nullable<bool> indicador_modificado_manual5 { get; set; }
        public Nullable<bool> indicador_modificado_manual6 { get; set; }
        public Nullable<bool> indicador_modificado_manual7 { get; set; }
        public Nullable<bool> indicador_modificado_manual8 { get; set; }
        public Nullable<bool> indicador_modificado_manual9 { get; set; }
        public Nullable<bool> indicador_pago_horas_suplementarias { get; set; }
        public bool indicador_permiso_dia_completo { get; set; }
        public bool indicador_permiso_recuperable { get; set; }
        public Nullable<bool> indicador_subsidio_vespertino { get; set; }
        public bool indicador_vacacion { get; set; }
        public Nullable<System.TimeSpan> marcacion_entrada { get; set; }
        public Nullable<System.TimeSpan> marcacion_entrada_receso { get; set; }
        public Nullable<System.TimeSpan> marcacion_entrada_reingreso1 { get; set; }
        public Nullable<System.TimeSpan> marcacion_entrada_reingreso2 { get; set; }
        public Nullable<System.TimeSpan> marcacion_salida { get; set; }
        public Nullable<System.TimeSpan> marcacion_salida_receso { get; set; }
        public Nullable<System.TimeSpan> marcacion_salida_reingreso1 { get; set; }
        public Nullable<System.TimeSpan> marcacion_salida_reingreso2 { get; set; }
        public Nullable<decimal> minutos_exceso_permiso { get; set; }
        public Nullable<System.TimeSpan> salida { get; set; }
        public Nullable<System.TimeSpan> salida_receso { get; set; }
        public Nullable<int> id_asistencia_padre { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_subsidio_empleado { get; set; }
        public Nullable<int> id_tipo_falta { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual tipo_falta tipo_falta { get; set; }
        public virtual subsidio_empleado subsidio_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asistencia> asistencia1 { get; set; }
        public virtual asistencia asistencia2 { get; set; }
    }
}
