//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atributo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public atributo()
        {
            this.asignacion_atributo = new HashSet<asignacion_atributo>();
            this.empresa_atributo = new HashSet<empresa_atributo>();
            this.producto = new HashSet<producto>();
            this.filtro_producto = new HashSet<filtro_producto>();
            this.lote = new HashSet<lote>();
            this.detalle_factura_cliente = new HashSet<detalle_factura_cliente>();
            this.detalle_version_lista_precios = new HashSet<detalle_version_lista_precios>();
            this.detalle_pedido_cliente = new HashSet<detalle_pedido_cliente>();
            this.lote1 = new HashSet<lote>();
            this.detalle_factura_cliente1 = new HashSet<detalle_factura_cliente>();
            this.lote2 = new HashSet<lote>();
            this.filtro_producto1 = new HashSet<filtro_producto>();
            this.producto1 = new HashSet<producto>();
            this.producto2 = new HashSet<producto>();
            this.detalle_pedido_cliente1 = new HashSet<detalle_pedido_cliente>();
            this.detalle_version_lista_precios1 = new HashSet<detalle_version_lista_precios>();
            this.organizacion_configuracion = new HashSet<organizacion_configuracion>();
            this.producto3 = new HashSet<producto>();
            this.lote3 = new HashSet<lote>();
            this.filtro_producto2 = new HashSet<filtro_producto>();
            this.orden_fabricacion = new HashSet<orden_fabricacion>();
            this.detalle_version_lista_precios2 = new HashSet<detalle_version_lista_precios>();
            this.organizacion_configuracion1 = new HashSet<organizacion_configuracion>();
            this.organizacion_configuracion2 = new HashSet<organizacion_configuracion>();
            this.organizacion_configuracion3 = new HashSet<organizacion_configuracion>();
            this.detalle_version_lista_precios3 = new HashSet<detalle_version_lista_precios>();
            this.producto4 = new HashSet<producto>();
            this.detalle_pedido_cliente2 = new HashSet<detalle_pedido_cliente>();
            this.detalle_pedido_cliente3 = new HashSet<detalle_pedido_cliente>();
            this.detalle_factura_cliente2 = new HashSet<detalle_factura_cliente>();
            this.organizacion_configuracion4 = new HashSet<organizacion_configuracion>();
            this.detalle_version_lista_precios4 = new HashSet<detalle_version_lista_precios>();
            this.filtro_producto3 = new HashSet<filtro_producto>();
            this.detalle_factura_cliente3 = new HashSet<detalle_factura_cliente>();
            this.organizacion_configuracion5 = new HashSet<organizacion_configuracion>();
            this.detalle_factura_cliente4 = new HashSet<detalle_factura_cliente>();
            this.lote4 = new HashSet<lote>();
            this.detalle_ajuste_prefactura_cliente = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.filtro_producto4 = new HashSet<filtro_producto>();
            this.detalle_ajuste_prefactura_cliente1 = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.detalle_ajuste_prefactura_cliente2 = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.producto5 = new HashSet<producto>();
            this.organizacion_configuracion6 = new HashSet<organizacion_configuracion>();
            this.lote5 = new HashSet<lote>();
            this.detalle_ajuste_prefactura_cliente3 = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.detalle_ajuste_prefactura_cliente4 = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.filtro_producto5 = new HashSet<filtro_producto>();
            this.organizacion_configuracion7 = new HashSet<organizacion_configuracion>();
            this.producto_atributo = new HashSet<producto_atributo>();
            this.detalle_factura_cliente5 = new HashSet<detalle_factura_cliente>();
            this.detalle_pedido_cliente4 = new HashSet<detalle_pedido_cliente>();
            this.detalle_ajuste_prefactura_cliente5 = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.detalle_factura_cliente6 = new HashSet<detalle_factura_cliente>();
            this.detalle_factura_cliente7 = new HashSet<detalle_factura_cliente>();
            this.producto6 = new HashSet<producto>();
            this.detalle_factura_cliente8 = new HashSet<detalle_factura_cliente>();
            this.detalle_pedido_cliente5 = new HashSet<detalle_pedido_cliente>();
            this.detalle_version_lista_precios5 = new HashSet<detalle_version_lista_precios>();
            this.detalle_ajuste_prefactura_cliente6 = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.detalle_version_lista_precios6 = new HashSet<detalle_version_lista_precios>();
            this.valor_atributo = new HashSet<valor_atributo>();
            this.filtro_producto6 = new HashSet<filtro_producto>();
            this.filtro_producto7 = new HashSet<filtro_producto>();
            this.detalle_version_lista_precios7 = new HashSet<detalle_version_lista_precios>();
            this.lote6 = new HashSet<lote>();
            this.producto7 = new HashSet<producto>();
            this.producto8 = new HashSet<producto>();
            this.filtro_producto8 = new HashSet<filtro_producto>();
            this.filtro_producto9 = new HashSet<filtro_producto>();
            this.detalle_version_lista_precios8 = new HashSet<detalle_version_lista_precios>();
            this.detalle_pedido_cliente6 = new HashSet<detalle_pedido_cliente>();
            this.detalle_ajuste_prefactura_cliente7 = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.detalle_factura_cliente9 = new HashSet<detalle_factura_cliente>();
            this.detalle_pedido_cliente7 = new HashSet<detalle_pedido_cliente>();
            this.detalle_pedido_cliente8 = new HashSet<detalle_pedido_cliente>();
            this.lote7 = new HashSet<lote>();
            this.detalle_version_lista_precios9 = new HashSet<detalle_version_lista_precios>();
            this.lote8 = new HashSet<lote>();
            this.detalle_ajuste_prefactura_cliente8 = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.organizacion_configuracion8 = new HashSet<organizacion_configuracion>();
            this.organizacion_configuracion9 = new HashSet<organizacion_configuracion>();
            this.detalle_pedido_cliente9 = new HashSet<detalle_pedido_cliente>();
            this.lote9 = new HashSet<lote>();
            this.detalle_ajuste_prefactura_cliente9 = new HashSet<detalle_ajuste_prefactura_cliente>();
            this.producto9 = new HashSet<producto>();
            this.conjunto_atributo = new HashSet<conjunto_atributo>();
        }
    
        public int id_atributo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<bool> indicador_cliente { get; set; }
        public bool indicador_impresion { get; set; }
        public bool indicador_instancia { get; set; }
        public Nullable<bool> indicador_producto { get; set; }
        public Nullable<bool> indicador_proveedor { get; set; }
        public bool indicador_requerido { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
        public int tipo_atributo { get; set; }
        public bool indicador_lista_precios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacion_atributo> asignacion_atributo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empresa_atributo> empresa_atributo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtro_producto> filtro_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_lista_precios> detalle_version_lista_precios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_cliente> detalle_pedido_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtro_producto> filtro_producto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_cliente> detalle_pedido_cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_lista_precios> detalle_version_lista_precios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacion_configuracion> organizacion_configuracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtro_producto> filtro_producto2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_fabricacion> orden_fabricacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_lista_precios> detalle_version_lista_precios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacion_configuracion> organizacion_configuracion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacion_configuracion> organizacion_configuracion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacion_configuracion> organizacion_configuracion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_lista_precios> detalle_version_lista_precios3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_cliente> detalle_pedido_cliente2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_cliente> detalle_pedido_cliente3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacion_configuracion> organizacion_configuracion4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_lista_precios> detalle_version_lista_precios4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtro_producto> filtro_producto3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacion_configuracion> organizacion_configuracion5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtro_producto> filtro_producto4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacion_configuracion> organizacion_configuracion6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtro_producto> filtro_producto5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacion_configuracion> organizacion_configuracion7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_atributo> producto_atributo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_cliente> detalle_pedido_cliente4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_cliente> detalle_pedido_cliente5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_lista_precios> detalle_version_lista_precios5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_lista_precios> detalle_version_lista_precios6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valor_atributo> valor_atributo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtro_producto> filtro_producto6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtro_producto> filtro_producto7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_lista_precios> detalle_version_lista_precios7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtro_producto> filtro_producto8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtro_producto> filtro_producto9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_lista_precios> detalle_version_lista_precios8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_cliente> detalle_pedido_cliente6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_cliente> detalle_pedido_cliente7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_cliente> detalle_pedido_cliente8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_lista_precios> detalle_version_lista_precios9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacion_configuracion> organizacion_configuracion8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organizacion_configuracion> organizacion_configuracion9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_cliente> detalle_pedido_cliente9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ajuste_prefactura_cliente> detalle_ajuste_prefactura_cliente9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conjunto_atributo> conjunto_atributo { get; set; }
    }
}
