//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carga_archivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carga_archivo()
        {
            this.ticket = new HashSet<ticket>();
        }
    
        public int id_carga_archivo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<bool> indicador_respaldo { get; set; }
        public string numero { get; set; }
        public Nullable<System.DateTime> periodo { get; set; }
        public string referencia_archivo { get; set; }
        public string tipo { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public int id_documento { get; set; }
        public Nullable<int> id_interfaz_contable_proceso { get; set; }
    
        public virtual asiento asiento { get; set; }
        public virtual documento documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> ticket { get; set; }
        public virtual interfaz_contable_proceso interfaz_contable_proceso { get; set; }
    }
}
