//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class centro_trabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public centro_trabajo()
        {
            this.maquina = new HashSet<maquina>();
            this.operacion_produccion = new HashSet<operacion_produccion>();
            this.tarea_produccion = new HashSet<tarea_produccion>();
        }
    
        public int id_centro_trabajo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_organizacion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
        public int tipo_centro_trabajo { get; set; }
        public int id_bodega_trabajo { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public int id_empleado_generico { get; set; }
    
        public virtual bodega bodega { get; set; }
        public virtual empleado_generico empleado_generico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maquina> maquina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operacion_produccion> operacion_produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarea_produccion> tarea_produccion { get; set; }
        public virtual departamento departamento { get; set; }
    }
}
