//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroCosto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentroCosto()
        {
            this.CentroCosto1 = new HashSet<CentroCosto>();
        }
    
        public string numero { get; set; }
        public int id_centro_costo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_organizacion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public bool indicador_movimiento { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
        public Nullable<int> id_centro_costo_padre { get; set; }
        public int id_nivel_centro_costo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentroCosto> CentroCosto1 { get; set; }
        public virtual CentroCosto CentroCosto2 { get; set; }
        public virtual nivel_centro_costo nivel_centro_costo { get; set; }
    }
}
