//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_principal
    {
        public int id_chat { get; set; }
        public int user_emisor { get; set; }
        public int user_receptor { get; set; }
        public string mensaje { get; set; }
        public string tipo { get; set; }
        public string ruta_archivo { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<int> estado_emisor { get; set; }
        public Nullable<int> estado_receptor { get; set; }
    }
}
