//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chq_postergado
    {
        public int id_chq_pstrgd { get; set; }
        public string codigo_chq_a_postergar { get; set; }
        public Nullable<System.DateTime> fecha_ant_a_postergacion { get; set; }
        public string codigo_chq_postergado { get; set; }
        public Nullable<System.DateTime> fecha_postergacion { get; set; }
        public string tipo_cambio { get; set; }
        public string usuario { get; set; }
    
        public virtual clnt_cobro_validado clnt_cobro_validado { get; set; }
        public virtual clnt_cobro_validado clnt_cobro_validado1 { get; set; }
    }
}
