//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion_cass
    {
        public int id_configuracion_cass { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
        public Nullable<int> id_comm_agcy { get; set; }
        public Nullable<int> id_credito_tributario_commision { get; set; }
        public Nullable<int> id_cuenta_por_cobrar_cass { get; set; }
        public Nullable<int> id_discount { get; set; }
        public Nullable<int> id_guia_collect_x { get; set; }
        public Nullable<int> id_iva_retenido { get; set; }
        public Nullable<int> id_manejo_carga_tarifa_cero { get; set; }
        public Nullable<int> id_retencion_flete_agencia_viaje_carga { get; set; }
        public Nullable<int> id_ventas_cass { get; set; }
    
        public virtual cuenta_contable cuenta_contable { get; set; }
        public virtual cuenta_contable cuenta_contable1 { get; set; }
        public virtual cuenta_contable cuenta_contable2 { get; set; }
        public virtual cuenta_contable cuenta_contable3 { get; set; }
        public virtual cuenta_contable cuenta_contable4 { get; set; }
        public virtual cuenta_contable cuenta_contable5 { get; set; }
        public virtual cuenta_contable cuenta_contable6 { get; set; }
        public virtual cuenta_contable cuenta_contable7 { get; set; }
        public virtual cuenta_contable cuenta_contable8 { get; set; }
    }
}
