//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion_carga_ticket
    {
        public int id_configuracion_carga_ticket { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string criterio { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string nombre { get; set; }
        public string nombre_etiqueta { get; set; }
        public Nullable<int> orden { get; set; }
        public string referencia { get; set; }
        public string referencia2 { get; set; }
        public string monto { get; set; }
        public Nullable<int> id_cuenta_contable_tkt_1 { get; set; }
        public Nullable<int> id_cuenta_contable_tkt_2 { get; set; }
    
        public virtual cuenta_contable cuenta_contable { get; set; }
        public virtual cuenta_contable cuenta_contable1 { get; set; }
    }
}
