//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumo_agil_mantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public consumo_agil_mantenimiento()
        {
            this.detalle_consumo_agil_mantenimiento = new HashSet<detalle_consumo_agil_mantenimiento>();
        }
    
        public int id_consumo_agil_mantenimiento { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> id_organizacion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string numero { get; set; }
        public int id_documento { get; set; }
        public int id_documento_orden { get; set; }
        public Nullable<int> id_orden_trabajo_mantenimiento { get; set; }
        public Nullable<int> id_responsable_salida_mercaderia { get; set; }
    
        public virtual documento documento { get; set; }
        public virtual responsable_salida_mercaderia responsable_salida_mercaderia { get; set; }
        public virtual documento documento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_consumo_agil_mantenimiento> detalle_consumo_agil_mantenimiento { get; set; }
        public virtual responsable_salida_mercaderia responsable_salida_mercaderia1 { get; set; }
    }
}
