//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato_arrendamiento_factura_contrato_arrendamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contrato_arrendamiento_factura_contrato_arrendamiento()
        {
            this.detalle_factura_cliente = new HashSet<detalle_factura_cliente>();
        }
    
        public int id_contrato_arrendamiento_factura_contrato_arrendamiento { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fechaDesde { get; set; }
        public Nullable<System.DateTime> fechaHasta { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public decimal valor { get; set; }
        public int id_detalle_contrato_arrendamiento { get; set; }
        public int id_detalles_factura_contrato_arrendamiento { get; set; }
    
        public virtual detalles_factura_contrato_arrendamiento detalles_factura_contrato_arrendamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente { get; set; }
        public virtual detalle_contrato_arrendamiento detalle_contrato_arrendamiento { get; set; }
    }
}
