//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class despacho_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public despacho_cliente()
        {
            this.detalle_hoja_ruta = new HashSet<detalle_hoja_ruta>();
            this.factura_cliente = new HashSet<factura_cliente>();
            this.guia_remision = new HashSet<guia_remision>();
            this.detalle_despacho_cliente = new HashSet<detalle_despacho_cliente>();
            this.despacho_cliente_unidad_manejo = new HashSet<despacho_cliente_unidad_manejo>();
            this.registro_peso = new HashSet<registro_peso>();
        }
    
        public int id_despacho_cliente { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string codigo_movil { get; set; }
        public string descripcion { get; set; }
        public string descripcion_anulacion { get; set; }
        public int estado { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_anulacion { get; set; }
        public Nullable<System.DateTime> fecha_contabilizacion { get; set; }
        public int id_organizacion { get; set; }
        public Nullable<bool> indicador_despacho_sugerido { get; set; }
        public Nullable<bool> indicador_generado_factura { get; set; }
        public Nullable<bool> indicador_generado_prefactura { get; set; }
        public string numero { get; set; }
        public string numero_guia_tramaco { get; set; }
        public string pdf { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public int id_direccion_empresa { get; set; }
        public int id_documento { get; set; }
        public int id_empresa { get; set; }
        public Nullable<int> id_interfaz_contable_proceso { get; set; }
        public Nullable<int> id_movimiento_inventario { get; set; }
        public Nullable<int> id_orden_despacho_cliente { get; set; }
        public Nullable<int> id_pedido_cliente { get; set; }
        public Nullable<int> id_prefactura_cliente { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public Nullable<int> id_responsable_salida_mercaderia { get; set; }
        public Nullable<int> id_subempresa { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<int> id_tipo_orden_despacho { get; set; }
        public Nullable<int> id_transportista { get; set; }
    
        public virtual asiento asiento { get; set; }
        public virtual transportista transportista { get; set; }
        public virtual movimiento_inventario movimiento_inventario { get; set; }
        public virtual responsable_salida_mercaderia responsable_salida_mercaderia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_hoja_ruta> detalle_hoja_ruta { get; set; }
        public virtual documento documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_cliente> factura_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guia_remision> guia_remision { get; set; }
        public virtual sucursal sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_despacho_cliente> detalle_despacho_cliente { get; set; }
        public virtual direccion_empresa direccion_empresa { get; set; }
        public virtual dimension_contable dimension_contable { get; set; }
        public virtual prefactura_cliente prefactura_cliente { get; set; }
        public virtual tipo_orden_despacho tipo_orden_despacho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<despacho_cliente_unidad_manejo> despacho_cliente_unidad_manejo { get; set; }
        public virtual orden_despacho_cliente orden_despacho_cliente { get; set; }
        public virtual pedido_cliente pedido_cliente { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual subempresa subempresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro_peso> registro_peso { get; set; }
        public virtual interfaz_contable_proceso interfaz_contable_proceso { get; set; }
    }
}
