//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_documento_digitalizado
    {
        public int id_detalle_documento_digitalizado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
        public string fichero { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<int> id_documento_digitalizado { get; set; }
        public Nullable<int> id_documento_digitalizado_categoria_empresa { get; set; }
        public Nullable<int> id_documento_digitalizado_departamento { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_producto { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual documento_digitalizado documento_digitalizado { get; set; }
        public virtual documento_digitalizado_categoria_empresa documento_digitalizado_categoria_empresa { get; set; }
        public virtual documento_digitalizado_departamento documento_digitalizado_departamento { get; set; }
        public virtual empresa empresa { get; set; }
    }
}
