//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_devolucion_proveedor_consignacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_devolucion_proveedor_consignacion()
        {
            this.inventario_producto = new HashSet<inventario_producto>();
            this.lectura_balanza = new HashSet<lectura_balanza>();
        }
    
        public int id_detalle_devolucion_proveedor_consignacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public decimal cantidad { get; set; }
        public Nullable<decimal> cantidad_unidad_informativa { get; set; }
        public string descripcion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public int id_bodega { get; set; }
        public Nullable<int> id_detalle_recepcion_proveedor { get; set; }
        public Nullable<int> id_devolucion_proveedor_consignacion { get; set; }
        public Nullable<int> id_lote { get; set; }
        public int id_producto { get; set; }
        public int id_unidad_compra { get; set; }
    
        public virtual bodega bodega { get; set; }
        public virtual devolucion_proveedor_consignacion devolucion_proveedor_consignacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_producto> inventario_producto { get; set; }
        public virtual lote lote { get; set; }
        public virtual unidad unidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lectura_balanza> lectura_balanza { get; set; }
        public virtual producto producto { get; set; }
        public virtual detalle_recepcion_proveedor detalle_recepcion_proveedor { get; set; }
    }
}
