//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_condicion_pago
    {
        public int id_detalle_condicion_pago { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public int dia_final { get; set; }
        public int dia_inicial { get; set; }
        public int dias_adicionales { get; set; }
        public string dia_mes_vencimiento { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public int id_condicion_pago { get; set; }
    
        public virtual condicion_pago condicion_pago { get; set; }
    }
}
