//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pago_comision
    {
        public int id_detalle_pago_comision { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public decimal base_comision { get; set; }
        public int diferencia_dias_comision { get; set; }
        public int forma_pago_comision_enum { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public decimal porcentaje_comision { get; set; }
        public decimal valor_comision { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_categoria_producto { get; set; }
        public int id_detalle_cobro { get; set; }
        public int id_factura_cliente { get; set; }
        public Nullable<int> id_pago_comision { get; set; }
        public Nullable<int> id_producto { get; set; }
        public int id_rango_dias_comision { get; set; }
        public Nullable<int> id_subcategoria_producto { get; set; }
    
        public virtual categoria_producto categoria_producto { get; set; }
        public virtual detalle_cobro detalle_cobro { get; set; }
        public virtual producto producto { get; set; }
        public virtual factura_cliente factura_cliente { get; set; }
        public virtual subcategoria_producto subcategoria_producto { get; set; }
        public virtual pago_comision pago_comision { get; set; }
        public virtual rango_dias_comision rango_dias_comision { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
