//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_historico_empleado
    {
        public int id_detalle_historico_empleado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_inicio_contrato_fijo { get; set; }
        public int horas_semana { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string numero_contrato { get; set; }
        public decimal porcentaje_capacidad_semanal { get; set; }
        public int id_historico_empleado { get; set; }
        public int id_tipo_contrato { get; set; }
    
        public virtual tipo_contrato tipo_contrato { get; set; }
        public virtual historico_empleado historico_empleado { get; set; }
    }
}
