//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_asiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_asiento()
        {
            this.movimiento_bancario = new HashSet<movimiento_bancario>();
        }
    
        public int id_detalle_asiento { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string beneficiario { get; set; }
        public Nullable<decimal> debe { get; set; }
        public string descripcion { get; set; }
        public string descripcion2 { get; set; }
        public string documento_referencia { get; set; }
        public Nullable<decimal> haber { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public byte[] traPlantillaDistribucionDimensionContable { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public int id_cuenta_contable { get; set; }
        public Nullable<int> id_dimension_contable1 { get; set; }
        public Nullable<int> id_dimension_contable2 { get; set; }
        public Nullable<int> id_dimension_contable3 { get; set; }
        public Nullable<int> id_dimension_contable4 { get; set; }
        public Nullable<int> id_dimension_contable5 { get; set; }
    
        public virtual asiento asiento { get; set; }
        public virtual cuenta_contable cuenta_contable { get; set; }
        public virtual dimension_contable dimension_contable { get; set; }
        public virtual dimension_contable dimension_contable1 { get; set; }
        public virtual dimension_contable dimension_contable2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_bancario> movimiento_bancario { get; set; }
        public virtual dimension_contable dimension_contable3 { get; set; }
        public virtual dimension_contable dimension_contable4 { get; set; }
    }
}
