//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_version_plan_comision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_version_plan_comision()
        {
            this.detalle_version_plan_comision_rango_dias = new HashSet<detalle_version_plan_comision_rango_dias>();
        }
    
        public int id_detalle_version_plan_comision { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public int forma_pago_comision_enum { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<int> id_categoria_producto { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_subcategoria_producto { get; set; }
        public int id_version_plan_comision { get; set; }
    
        public virtual categoria_producto categoria_producto { get; set; }
        public virtual producto producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_version_plan_comision_rango_dias> detalle_version_plan_comision_rango_dias { get; set; }
        public virtual version_plan_comision version_plan_comision { get; set; }
        public virtual subcategoria_producto subcategoria_producto { get; set; }
    }
}
