//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_orden_salida_material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_orden_salida_material()
        {
            this.detalle_movimiento_inventario = new HashSet<detalle_movimiento_inventario>();
            this.detalle_orden_salida_material_orden_fabricacion = new HashSet<detalle_orden_salida_material_orden_fabricacion>();
            this.detalle_registro_peso = new HashSet<detalle_registro_peso>();
            this.lectura_balanza = new HashSet<lectura_balanza>();
            this.detalle_orden_salida_material1 = new HashSet<detalle_orden_salida_material>();
            this.detalle_orden_salida_material_bloque = new HashSet<detalle_orden_salida_material_bloque>();
        }
    
        public int id_detalle_orden_salida_material { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public decimal cantidad { get; set; }
        public decimal cantidad_a_devolver { get; set; }
        public decimal cantidad_adicional { get; set; }
        public Nullable<decimal> cantidad_anulada_orden_fabricacion { get; set; }
        public Nullable<decimal> cantidad_desecho { get; set; }
        public decimal cantidad_deseleccionada { get; set; }
        public decimal cantidad_despachada { get; set; }
        public decimal cantidad_devuelta { get; set; }
        public decimal cantidad_por_despachar { get; set; }
        public Nullable<decimal> cantidad_unidad_informativa_desecho { get; set; }
        public Nullable<decimal> cantidad_unidad_informativa_descpacho { get; set; }
        public Nullable<decimal> cantidad_unidad_informativa_devolucion { get; set; }
        public decimal cantidad_utilizada { get; set; }
        public string codigo_variedad_flor { get; set; }
        public string codigo_zona { get; set; }
        public Nullable<int> criterio_siembra { get; set; }
        public string descripcion { get; set; }
        public decimal extencion_cama { get; set; }
        public decimal factor { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<int> id_variedad_flor { get; set; }
        public Nullable<int> id_zona { get; set; }
        public bool indicador_automatico { get; set; }
        public bool indicador_consumo_directo { get; set; }
        public Nullable<bool> indicador_principal { get; set; }
        public bool indicador_variedad_destino { get; set; }
        public bool indicador_zona_destino { get; set; }
        public string nombre_variedad_flor { get; set; }
        public string nombre_zona { get; set; }
        public Nullable<int> id_bodega { get; set; }
        public Nullable<int> id_bodega_origen { get; set; }
        public Nullable<int> id_destino_costo { get; set; }
        public Nullable<int> id_detalle_orden_salida_material_padre { get; set; }
        public Nullable<int> id_lote { get; set; }
        public Nullable<int> id_orden_fabricacion { get; set; }
        public Nullable<int> id_orden_salida_material { get; set; }
        public int id_producto { get; set; }
        public int id_unidad { get; set; }
    
        public virtual bodega bodega { get; set; }
        public virtual bodega bodega1 { get; set; }
        public virtual destino_costo destino_costo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_movimiento_inventario> detalle_movimiento_inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_orden_salida_material_orden_fabricacion> detalle_orden_salida_material_orden_fabricacion { get; set; }
        public virtual lote lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_registro_peso> detalle_registro_peso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lectura_balanza> lectura_balanza { get; set; }
        public virtual orden_salida_material orden_salida_material { get; set; }
        public virtual unidad unidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_orden_salida_material> detalle_orden_salida_material1 { get; set; }
        public virtual detalle_orden_salida_material detalle_orden_salida_material2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_orden_salida_material_bloque> detalle_orden_salida_material_bloque { get; set; }
        public virtual producto producto { get; set; }
        public virtual orden_fabricacion orden_fabricacion { get; set; }
    }
}
