//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_recepcion_proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_recepcion_proveedor()
        {
            this.detalle_devolucion_proveedor_consignacion = new HashSet<detalle_devolucion_proveedor_consignacion>();
            this.detalle_factura_proveedor = new HashSet<detalle_factura_proveedor>();
            this.lectura_balanza = new HashSet<lectura_balanza>();
            this.inventario_producto = new HashSet<inventario_producto>();
            this.inventario_producto1 = new HashSet<inventario_producto>();
        }
    
        public int id_detalle_recepcion_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public decimal cantidad { get; set; }
        public Nullable<decimal> cantidad_devuelta { get; set; }
        public decimal cantidad_devuelta_consignacion { get; set; }
        public int cantidad_etiqueta { get; set; }
        public decimal cantidad_faltante_calidad { get; set; }
        public decimal cantidad_liberado_calidad { get; set; }
        public Nullable<decimal> cantidad_unidad_informativa { get; set; }
        public string descripcion { get; set; }
        public string descripcion2 { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_aprobado_calidad { get; set; }
        public bool indicador_creado_calidad { get; set; }
        public bool indicador_rechazado_calidad { get; set; }
        public int id_bodega { get; set; }
        public Nullable<int> id_detalle_factura_proveedor { get; set; }
        public Nullable<int> id_detalle_pedido_proveedor { get; set; }
        public Nullable<int> id_lote { get; set; }
        public int id_producto { get; set; }
        public Nullable<int> id_recepcion_proveedor { get; set; }
        public Nullable<int> id_transformacion_automatica { get; set; }
        public int id_unidad_compra { get; set; }
    
        public virtual bodega bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_devolucion_proveedor_consignacion> detalle_devolucion_proveedor_consignacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_proveedor> detalle_factura_proveedor { get; set; }
        public virtual detalle_factura_proveedor detalle_factura_proveedor1 { get; set; }
        public virtual detalle_pedido_proveedor detalle_pedido_proveedor { get; set; }
        public virtual movimiento_inventario movimiento_inventario { get; set; }
        public virtual unidad unidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lectura_balanza> lectura_balanza { get; set; }
        public virtual recepcion_proveedor recepcion_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_producto> inventario_producto { get; set; }
        public virtual lote lote { get; set; }
        public virtual producto producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_producto> inventario_producto1 { get; set; }
    }
}
