//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_presupuesto_formulacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_presupuesto_formulacion()
        {
            this.detalle_orden_fabricacion_material = new HashSet<detalle_orden_fabricacion_material>();
        }
    
        public int id_detalle_presupuesto_formulacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public decimal cantidad_batch { get; set; }
        public string descripcion_formula { get; set; }
        public int estado { get; set; }
        public int id_organizacion { get; set; }
        public bool indicador_formulada { get; set; }
        public decimal valor_estimado_producir01 { get; set; }
        public decimal valor_estimado_producir02 { get; set; }
        public decimal valor_estimado_producir03 { get; set; }
        public decimal valor_estimado_producir04 { get; set; }
        public decimal valor_estimado_producir05 { get; set; }
        public decimal valor_estimado_producir06 { get; set; }
        public decimal valor_estimado_producir07 { get; set; }
        public decimal valor_estimado_producir08 { get; set; }
        public decimal valor_estimado_producir09 { get; set; }
        public decimal valor_estimado_producir10 { get; set; }
        public decimal valor_estimado_producir11 { get; set; }
        public decimal valor_estimado_producir12 { get; set; }
        public decimal valor_historico01 { get; set; }
        public decimal valor_historico02 { get; set; }
        public decimal valor_historico03 { get; set; }
        public decimal valor_historico04 { get; set; }
        public decimal valor_historico05 { get; set; }
        public decimal valor_historico06 { get; set; }
        public decimal valor_historico07 { get; set; }
        public decimal valor_historico08 { get; set; }
        public decimal valor_historico09 { get; set; }
        public decimal valor_historico10 { get; set; }
        public decimal valor_historico11 { get; set; }
        public decimal valor_historico12 { get; set; }
        public decimal valor_historico_proyectado01 { get; set; }
        public decimal valor_historico_proyectado02 { get; set; }
        public decimal valor_historico_proyectado03 { get; set; }
        public decimal valor_historico_proyectado04 { get; set; }
        public decimal valor_historico_proyectado05 { get; set; }
        public decimal valor_historico_proyectado06 { get; set; }
        public decimal valor_historico_proyectado07 { get; set; }
        public decimal valor_historico_proyectado08 { get; set; }
        public decimal valor_historico_proyectado09 { get; set; }
        public decimal valor_historico_proyectado10 { get; set; }
        public decimal valor_historico_proyectado11 { get; set; }
        public decimal valor_historico_proyectado12 { get; set; }
        public Nullable<int> id_orden_fabricacion_formula { get; set; }
        public Nullable<int> id_presupuesto_formulacion { get; set; }
        public int id_producto { get; set; }
        public Nullable<int> id_producto_pp { get; set; }
        public int id_sucursal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_orden_fabricacion_material> detalle_orden_fabricacion_material { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual orden_fabricacion orden_fabricacion { get; set; }
        public virtual presupuesto_formulacion presupuesto_formulacion { get; set; }
        public virtual producto producto { get; set; }
        public virtual producto producto1 { get; set; }
    }
}
