//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pago
    {
        public int id_detalle_pago { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public decimal valor { get; set; }
        public int id_cuenta_por_pagar { get; set; }
        public Nullable<int> id_detalle_orden_pago_proveedor { get; set; }
        public Nullable<int> id_detalle_pago_cash { get; set; }
        public Nullable<int> id_pago { get; set; }
    
        public virtual cuenta_por_pagar cuenta_por_pagar { get; set; }
        public virtual detalle_orden_pago_proveedor detalle_orden_pago_proveedor { get; set; }
        public virtual detalle_pago_cash detalle_pago_cash { get; set; }
        public virtual pago pago { get; set; }
    }
}
