//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_ficha_tecnica_pago_cash
    {
        public int id_detalle_ficha_tecnica_pago_cash { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string caracter_relleno { get; set; }
        public string descripcion { get; set; }
        public string etiqueta_ficha_tecnica { get; set; }
        public string formato { get; set; }
        public int id_organizacion { get; set; }
        public Nullable<bool> indicador_valor { get; set; }
        public int indice_inicio { get; set; }
        public int longitud { get; set; }
        public string nemonico { get; set; }
        public int orden { get; set; }
        public bool relleno_derecha { get; set; }
        public string tipo_atributo { get; set; }
        public string valor_detalle { get; set; }
        public int id_ficha_tecnica_pago_cash { get; set; }
    
        public virtual ficha_tecnica_pago_cash ficha_tecnica_pago_cash { get; set; }
    }
}
