//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pago_cash
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_pago_cash()
        {
            this.detalle_pago = new HashSet<detalle_pago>();
        }
    
        public int id_detalle_pago_cash { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string ciudad_empleado { get; set; }
        public string codigo_banco { get; set; }
        public string codigo_banco_cuenta_bancaria_empleado { get; set; }
        public string cuenta_bancaria_empleado { get; set; }
        public string cuenta_bancaria_empresa { get; set; }
        public string descripcion { get; set; }
        public string direccion_empleado { get; set; }
        public string documento_referencia { get; set; }
        public Nullable<System.DateTime> fecha_contabilizacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string identificacion_empleado { get; set; }
        public bool indicador_aprobado { get; set; }
        public bool indicador_procesado { get; set; }
        public string nombre_banco { get; set; }
        public string referencia_pago_empleado { get; set; }
        public string telefono_empleado { get; set; }
        public string tipo_cuenta_bancaria { get; set; }
        public string tipo_servicio_cuenta_bancaria { get; set; }
        public decimal valor { get; set; }
        public Nullable<int> id_cuenta_por_pagar { get; set; }
        public Nullable<int> id_detalle_orden_pago_proveedor { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_pago { get; set; }
        public Nullable<int> id_pago_cash { get; set; }
        public Nullable<int> id_persona_responsable { get; set; }
        public Nullable<int> id_proveedor { get; set; }
    
        public virtual cuenta_por_pagar cuenta_por_pagar { get; set; }
        public virtual detalle_orden_pago_proveedor detalle_orden_pago_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pago> detalle_pago { get; set; }
        public virtual responsable_salida_mercaderia responsable_salida_mercaderia { get; set; }
        public virtual pago pago { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual pago_cash pago_cash { get; set; }
    }
}
