//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_presupuesto_mantenimiento
    {
        public int id_detalle_presupuesto_mantenimiento { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> fecha_real { get; set; }
        public Nullable<System.DateTime> fecha_estimada { get; set; }
        public bool indicador_padre { get; set; }
        public int id_actividad_mantenimiento { get; set; }
        public int id_componente_equipo { get; set; }
        public int id_equipo { get; set; }
        public Nullable<int> id_presupuesto_mantenimiento { get; set; }
    
        public virtual actividad_mantenimiento actividad_mantenimiento { get; set; }
        public virtual componente_equipo componente_equipo { get; set; }
        public virtual presupuesto_mantenimiento presupuesto_mantenimiento { get; set; }
        public virtual equipo equipo { get; set; }
    }
}
