//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_plan_produccion
    {
        public int id_detalle_plan_produccion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int batch_domingo { get; set; }
        public int batch_jueves { get; set; }
        public int batch_lunes { get; set; }
        public int batch_martes { get; set; }
        public int batch_miercoles { get; set; }
        public int batch_sabado { get; set; }
        public int batch_viernes { get; set; }
        public decimal cantidad_requerida_semana { get; set; }
        public decimal factor_cambio { get; set; }
        public decimal factor_crecimiento { get; set; }
        public Nullable<int> id_organizacion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public bool indicador_plan_maestro_domingo { get; set; }
        public bool indicador_plan_maestro_jueves { get; set; }
        public bool indicador_plan_maestro_lunes { get; set; }
        public bool indicador_plan_maestro_martes { get; set; }
        public bool indicador_plan_maestro_miercoles { get; set; }
        public bool indicador_plan_maestro_sabado { get; set; }
        public bool indicador_plan_maestro_viernes { get; set; }
        public decimal saldo_domingo { get; set; }
        public decimal saldo_inicial { get; set; }
        public decimal saldo_jueves { get; set; }
        public decimal saldo_lunes { get; set; }
        public decimal saldo_martes { get; set; }
        public decimal saldo_miercoles { get; set; }
        public decimal saldo_sabado { get; set; }
        public decimal saldo_viernes { get; set; }
        public decimal stock_minimo { get; set; }
        public decimal venta_domingo { get; set; }
        public decimal venta_domingo_anterior { get; set; }
        public decimal venta_jueves { get; set; }
        public decimal venta_jueves_anterior { get; set; }
        public decimal venta_lunes { get; set; }
        public decimal venta_lunes_anterior { get; set; }
        public decimal venta_martes { get; set; }
        public decimal venta_martes_anterior { get; set; }
        public decimal venta_miercoles { get; set; }
        public decimal venta_miercoles_anterior { get; set; }
        public decimal venta_sabado { get; set; }
        public decimal venta_sabado_anterior { get; set; }
        public decimal venta_viernes { get; set; }
        public decimal venta_viernes_anterior { get; set; }
        public Nullable<int> id_lote { get; set; }
        public int id_plan_produccion { get; set; }
        public int id_producto { get; set; }
        public int id_ruta_fabricacion { get; set; }
        public int id_unidad_stock { get; set; }
    
        public virtual unidad unidad { get; set; }
        public virtual plan_produccion plan_produccion { get; set; }
        public virtual lote lote { get; set; }
        public virtual ruta_fabricacion ruta_fabricacion { get; set; }
        public virtual producto producto { get; set; }
    }
}
