//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_componente_costo
    {
        public int id_detalle_componente_costo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public int valor_calculo { get; set; }
        public Nullable<int> id_componente_costo { get; set; }
        public int id_cuenta_contable { get; set; }
        public Nullable<int> id_cuenta_contable_cierre { get; set; }
    
        public virtual componente_costo componente_costo { get; set; }
        public virtual cuenta_contable cuenta_contable { get; set; }
        public virtual cuenta_contable cuenta_contable1 { get; set; }
    }
}
