//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_costo_fabricacion
    {
        public int id_detalle_costo_fabricacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public decimal cantidad_fabricada_mes { get; set; }
        public decimal costo_depreciacion_asignado_mes { get; set; }
        public decimal costo_depreciacion_inicial { get; set; }
        public decimal costo_depreciacion_mes { get; set; }
        public decimal costo_depreciacion_pendiente { get; set; }
        public decimal costo_indirectos_asignado_mes { get; set; }
        public decimal costo_indirectos_inicial { get; set; }
        public decimal costo_indirectos_mes { get; set; }
        public decimal costo_indirectos_pendiente { get; set; }
        public decimal costo_mano_obra_asignado_mes { get; set; }
        public decimal costo_mano_obra_inicial { get; set; }
        public decimal costo_mano_obra_mes { get; set; }
        public decimal costo_mano_obra_pendiente { get; set; }
        public decimal costo_materiales_asignado_mes { get; set; }
        public decimal costo_materiales_inicial { get; set; }
        public decimal costo_materiales_mes { get; set; }
        public decimal costo_materiales_pendiente { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public int id_costos_de_fabricacion { get; set; }
        public int id_orden_fabricacion { get; set; }
    
        public virtual costos_de_fabricacion costos_de_fabricacion { get; set; }
        public virtual orden_fabricacion orden_fabricacion { get; set; }
    }
}
