//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura_cliente_acumulacion_puntos
    {
        public int id_detalle_factura_cliente_acumulacion_puntos { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public decimal precio_total { get; set; }
        public decimal puntos { get; set; }
        public decimal puntos_informativo { get; set; }
        public decimal saldo_puntos { get; set; }
        public decimal saldo_valor_puntos { get; set; }
        public decimal valor_informativo { get; set; }
        public decimal valor_por_punto_informativo { get; set; }
        public decimal valor_puntos { get; set; }
        public int id_factura_cliente { get; set; }
        public int id_producto { get; set; }
    
        public virtual factura_cliente factura_cliente { get; set; }
        public virtual producto producto { get; set; }
    }
}
