//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_permiso_empleado
    {
        public int id_detalle_permiso_empleado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_permiso { get; set; }
        public System.TimeSpan hora_desde { get; set; }
        public Nullable<System.TimeSpan> hora_hasta { get; set; }
        public decimal horas { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_dia_completo { get; set; }
        public Nullable<decimal> minutos_exceso { get; set; }
        public Nullable<int> id_permiso_empleado { get; set; }
    
        public virtual permiso_empleado permiso_empleado { get; set; }
    }
}
