//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_despacho_factura_cliente
    {
        public int id_detalle_despacho_factura_cliente { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<int> id_detalle_despacho_cliente { get; set; }
        public Nullable<int> id_detalle_factura_cliente { get; set; }
    
        public virtual detalle_despacho_cliente detalle_despacho_cliente { get; set; }
        public virtual detalle_factura_cliente detalle_factura_cliente { get; set; }
    }
}
