//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dimension_contable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dimension_contable()
        {
            this.activo_fijo = new HashSet<activo_fijo>();
            this.asiento = new HashSet<asiento>();
            this.criterio_distribucion = new HashSet<criterio_distribucion>();
            this.criterio_distribucion1 = new HashSet<criterio_distribucion>();
            this.criterio_distribucion2 = new HashSet<criterio_distribucion>();
            this.criterio_distribucion3 = new HashSet<criterio_distribucion>();
            this.criterio_distribucion4 = new HashSet<criterio_distribucion>();
            this.cuenta_contable = new HashSet<cuenta_contable>();
            this.cuenta_contable_dimension_contable = new HashSet<cuenta_contable_dimension_contable>();
            this.despacho_cliente = new HashSet<despacho_cliente>();
            this.detalle_asiento = new HashSet<detalle_asiento>();
            this.detalle_asiento1 = new HashSet<detalle_asiento>();
            this.detalle_asiento2 = new HashSet<detalle_asiento>();
            this.detalle_asiento3 = new HashSet<detalle_asiento>();
            this.detalle_asiento4 = new HashSet<detalle_asiento>();
            this.detalle_componente_costo_distribucion = new HashSet<detalle_componente_costo_distribucion>();
            this.detalle_componente_costo_distribucion1 = new HashSet<detalle_componente_costo_distribucion>();
            this.detalle_componente_costo_distribucion2 = new HashSet<detalle_componente_costo_distribucion>();
            this.detalle_componente_costo_distribucion3 = new HashSet<detalle_componente_costo_distribucion>();
            this.detalle_componente_costo_distribucion4 = new HashSet<detalle_componente_costo_distribucion>();
            this.detalle_compra_caja_chica = new HashSet<detalle_compra_caja_chica>();
            this.detalle_compra_caja_chica1 = new HashSet<detalle_compra_caja_chica>();
            this.detalle_compra_caja_chica2 = new HashSet<detalle_compra_caja_chica>();
            this.detalle_compra_caja_chica3 = new HashSet<detalle_compra_caja_chica>();
            this.detalle_compra_caja_chica4 = new HashSet<detalle_compra_caja_chica>();
            this.detalle_forma_cobro = new HashSet<detalle_forma_cobro>();
            this.detalle_forma_cobro1 = new HashSet<detalle_forma_cobro>();
            this.detalle_forma_cobro2 = new HashSet<detalle_forma_cobro>();
            this.detalle_forma_cobro3 = new HashSet<detalle_forma_cobro>();
            this.detalle_forma_cobro4 = new HashSet<detalle_forma_cobro>();
            this.detalle_movimiento_partida_presupuestaria = new HashSet<detalle_movimiento_partida_presupuestaria>();
            this.detalle_movimiento_partida_presupuestaria1 = new HashSet<detalle_movimiento_partida_presupuestaria>();
            this.detalle_movimiento_presupuestaria = new HashSet<detalle_movimiento_presupuestaria>();
            this.detalle_movimiento_presupuestaria1 = new HashSet<detalle_movimiento_presupuestaria>();
            this.detalle_pedido_proveedor = new HashSet<detalle_pedido_proveedor>();
            this.detalle_pedido_proveedor1 = new HashSet<detalle_pedido_proveedor>();
            this.detalle_pedido_proveedor2 = new HashSet<detalle_pedido_proveedor>();
            this.detalle_pedido_proveedor3 = new HashSet<detalle_pedido_proveedor>();
            this.detalle_pedido_proveedor4 = new HashSet<detalle_pedido_proveedor>();
            this.detalle_plantilla_asiento = new HashSet<detalle_plantilla_asiento>();
            this.detalle_plantilla_asiento1 = new HashSet<detalle_plantilla_asiento>();
            this.detalle_plantilla_asiento2 = new HashSet<detalle_plantilla_asiento>();
            this.detalle_plantilla_asiento3 = new HashSet<detalle_plantilla_asiento>();
            this.detalle_plantilla_asiento4 = new HashSet<detalle_plantilla_asiento>();
            this.detalle_plantilla_distribucion_dimension_contable = new HashSet<detalle_plantilla_distribucion_dimension_contable>();
            this.detalle_plantilla_distribucion_dimension_contable1 = new HashSet<detalle_plantilla_distribucion_dimension_contable>();
            this.detalle_plantilla_distribucion_dimension_contable2 = new HashSet<detalle_plantilla_distribucion_dimension_contable>();
            this.detalle_plantilla_distribucion_dimension_contable3 = new HashSet<detalle_plantilla_distribucion_dimension_contable>();
            this.detalle_plantilla_distribucion_dimension_contable4 = new HashSet<detalle_plantilla_distribucion_dimension_contable>();
            this.detalle_presupuesto = new HashSet<detalle_presupuesto>();
            this.detalle_presupuesto_compra = new HashSet<detalle_presupuesto_compra>();
            this.detalle_solicitud_compra = new HashSet<detalle_solicitud_compra>();
            this.factura_cliente = new HashSet<factura_cliente>();
            this.gasto_producto_factura_proveedor = new HashSet<gasto_producto_factura_proveedor>();
            this.pago_rol_empleado = new HashSet<pago_rol_empleado>();
            this.pedido_proveedor = new HashSet<pedido_proveedor>();
            this.gasto_producto_factura_proveedor1 = new HashSet<gasto_producto_factura_proveedor>();
            this.inventario_producto = new HashSet<inventario_producto>();
            this.empleado_centro_costo = new HashSet<empleado_centro_costo>();
            this.pedido_cliente = new HashSet<pedido_cliente>();
            this.gasto_producto_factura_proveedor2 = new HashSet<gasto_producto_factura_proveedor>();
            this.movimiento_inventario = new HashSet<movimiento_inventario>();
            this.gasto_producto_factura_proveedor3 = new HashSet<gasto_producto_factura_proveedor>();
            this.usuario_dimension_contable = new HashSet<usuario_dimension_contable>();
            this.empleado = new HashSet<empleado>();
            this.dimension_contable1 = new HashSet<dimension_contable>();
            this.factura_proveedor = new HashSet<factura_proveedor>();
            this.recepcion_proveedor = new HashSet<recepcion_proveedor>();
            this.gasto_producto_factura_proveedor4 = new HashSet<gasto_producto_factura_proveedor>();
            this.equipo = new HashSet<equipo>();
        }
    
        public int id_dimension_contable { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public bool distribucion_empleado { get; set; }
        public Nullable<System.DateTime> fecha_contrato { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_movimiento { get; set; }
        public string mascara { get; set; }
        public string nombre { get; set; }
        public string numero { get; set; }
        public bool predeterminado { get; set; }
        public int tipo_acceso_contable { get; set; }
        public Nullable<int> id_dimension_padre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activo_fijo> activo_fijo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asiento> asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<criterio_distribucion> criterio_distribucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<criterio_distribucion> criterio_distribucion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<criterio_distribucion> criterio_distribucion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<criterio_distribucion> criterio_distribucion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<criterio_distribucion> criterio_distribucion4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuenta_contable> cuenta_contable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuenta_contable_dimension_contable> cuenta_contable_dimension_contable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<despacho_cliente> despacho_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_asiento> detalle_asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_asiento> detalle_asiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_asiento> detalle_asiento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_asiento> detalle_asiento3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_asiento> detalle_asiento4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_componente_costo_distribucion> detalle_componente_costo_distribucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_componente_costo_distribucion> detalle_componente_costo_distribucion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_componente_costo_distribucion> detalle_componente_costo_distribucion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_componente_costo_distribucion> detalle_componente_costo_distribucion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_componente_costo_distribucion> detalle_componente_costo_distribucion4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_compra_caja_chica> detalle_compra_caja_chica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_compra_caja_chica> detalle_compra_caja_chica1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_compra_caja_chica> detalle_compra_caja_chica2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_compra_caja_chica> detalle_compra_caja_chica3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_compra_caja_chica> detalle_compra_caja_chica4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_forma_cobro> detalle_forma_cobro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_forma_cobro> detalle_forma_cobro1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_forma_cobro> detalle_forma_cobro2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_forma_cobro> detalle_forma_cobro3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_forma_cobro> detalle_forma_cobro4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_movimiento_partida_presupuestaria> detalle_movimiento_partida_presupuestaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_movimiento_partida_presupuestaria> detalle_movimiento_partida_presupuestaria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_movimiento_presupuestaria> detalle_movimiento_presupuestaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_movimiento_presupuestaria> detalle_movimiento_presupuestaria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_proveedor> detalle_pedido_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_proveedor> detalle_pedido_proveedor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_proveedor> detalle_pedido_proveedor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_proveedor> detalle_pedido_proveedor3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido_proveedor> detalle_pedido_proveedor4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plantilla_asiento> detalle_plantilla_asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plantilla_asiento> detalle_plantilla_asiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plantilla_asiento> detalle_plantilla_asiento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plantilla_asiento> detalle_plantilla_asiento3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plantilla_asiento> detalle_plantilla_asiento4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plantilla_distribucion_dimension_contable> detalle_plantilla_distribucion_dimension_contable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plantilla_distribucion_dimension_contable> detalle_plantilla_distribucion_dimension_contable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plantilla_distribucion_dimension_contable> detalle_plantilla_distribucion_dimension_contable2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plantilla_distribucion_dimension_contable> detalle_plantilla_distribucion_dimension_contable3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plantilla_distribucion_dimension_contable> detalle_plantilla_distribucion_dimension_contable4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_presupuesto> detalle_presupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_presupuesto_compra> detalle_presupuesto_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_solicitud_compra> detalle_solicitud_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_cliente> factura_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gasto_producto_factura_proveedor> gasto_producto_factura_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_rol_empleado> pago_rol_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_proveedor> pedido_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gasto_producto_factura_proveedor> gasto_producto_factura_proveedor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_producto> inventario_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado_centro_costo> empleado_centro_costo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_cliente> pedido_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gasto_producto_factura_proveedor> gasto_producto_factura_proveedor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_inventario> movimiento_inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gasto_producto_factura_proveedor> gasto_producto_factura_proveedor3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_dimension_contable> usuario_dimension_contable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dimension_contable> dimension_contable1 { get; set; }
        public virtual dimension_contable dimension_contable2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_proveedor> factura_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recepcion_proveedor> recepcion_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gasto_producto_factura_proveedor> gasto_producto_factura_proveedor4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipo> equipo { get; set; }
    }
}
