//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento_contabilizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documento_contabilizacion()
        {
            this.criterio_contabilizacion = new HashSet<criterio_contabilizacion>();
            this.documento_contabilizacion1 = new HashSet<documento_contabilizacion>();
        }
    
        public int id_documento_contabilizacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public bool debe { get; set; }
        public int documento_base { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public int proceso_contabilizacion { get; set; }
        public bool reversa_proceso { get; set; }
        public Nullable<int> id_documento_contabilizacion_padre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<criterio_contabilizacion> criterio_contabilizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento_contabilizacion> documento_contabilizacion1 { get; set; }
        public virtual documento_contabilizacion documento_contabilizacion2 { get; set; }
    }
}
