//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documento()
        {
            this.amortizacion = new HashSet<amortizacion>();
            this.anticipo_cliente = new HashSet<anticipo_cliente>();
            this.anticipo_cliente1 = new HashSet<anticipo_cliente>();
            this.anticipo_proveedor = new HashSet<anticipo_proveedor>();
            this.anticipo_proveedor1 = new HashSet<anticipo_proveedor>();
            this.asiento = new HashSet<asiento>();
            this.autorizacion_documento_SRI = new HashSet<autorizacion_documento_SRI>();
            this.caja_chica = new HashSet<caja_chica>();
            this.calidad = new HashSet<calidad>();
            this.carga_archivo = new HashSet<carga_archivo>();
            this.carta_porte_internacional_carretera = new HashSet<carta_porte_internacional_carretera>();
            this.cass = new HashSet<cass>();
            this.cobro = new HashSet<cobro>();
            this.compra_caja_chica = new HashSet<compra_caja_chica>();
            this.configuracion_credito_tributario = new HashSet<configuracion_credito_tributario>();
            this.consumo_agil_mantenimiento = new HashSet<consumo_agil_mantenimiento>();
            this.consumo_agil_mantenimiento1 = new HashSet<consumo_agil_mantenimiento>();
            this.contrato_arrendamiento = new HashSet<contrato_arrendamiento>();
            this.contrato_venta = new HashSet<contrato_venta>();
            this.criterio_contabilizacion = new HashSet<criterio_contabilizacion>();
            this.criterio_distribucion = new HashSet<criterio_distribucion>();
            this.depreciacion = new HashSet<depreciacion>();
            this.despacho_cliente = new HashSet<despacho_cliente>();
            this.detalle_vacacion = new HashSet<detalle_vacacion>();
            this.devolucion_proveedor_consignacion = new HashSet<devolucion_proveedor_consignacion>();
            this.interfaz_contable_proceso = new HashSet<interfaz_contable_proceso>();
            this.guia_remision = new HashSet<guia_remision>();
            this.pago_cash = new HashSet<pago_cash>();
            this.factura_cliente = new HashSet<factura_cliente>();
            this.pago = new HashSet<pago>();
            this.factura_proveedorSRI = new HashSet<factura_proveedorSRI>();
            this.liquidacion_anticipo_proveedor = new HashSet<liquidacion_anticipo_proveedor>();
            this.orden_servicio_mantenimiento = new HashSet<orden_servicio_mantenimiento>();
            this.movimiento_inventario = new HashSet<movimiento_inventario>();
            this.tipo_prestamo = new HashSet<tipo_prestamo>();
            this.movimiento_partida_presupuestaria = new HashSet<movimiento_partida_presupuestaria>();
            this.hoja_ruta = new HashSet<hoja_ruta>();
            this.pago_rol = new HashSet<pago_rol>();
            this.pago_empleado = new HashSet<pago_empleado>();
            this.novedad_empleado = new HashSet<novedad_empleado>();
            this.documento1 = new HashSet<documento>();
            this.precio_rango_cif = new HashSet<precio_rango_cif>();
            this.orden_salida_material = new HashSet<orden_salida_material>();
            this.orden_fabricacion = new HashSet<orden_fabricacion>();
            this.orden_pago_proveedor = new HashSet<orden_pago_proveedor>();
            this.orden_pago_proveedor1 = new HashSet<orden_pago_proveedor>();
            this.movimiento_inventario1 = new HashSet<movimiento_inventario>();
            this.pago_cash1 = new HashSet<pago_cash>();
            this.solicitud_compra = new HashSet<solicitud_compra>();
            this.pre_devolucion_cliente = new HashSet<pre_devolucion_cliente>();
            this.prefactura_cliente = new HashSet<prefactura_cliente>();
            this.redimir_puntos = new HashSet<redimir_puntos>();
            this.liquidacion_anticipo_cliente = new HashSet<liquidacion_anticipo_cliente>();
            this.pedido_proveedor = new HashSet<pedido_proveedor>();
            this.toma_fisica = new HashSet<toma_fisica>();
            this.registro_peso = new HashSet<registro_peso>();
            this.recepcion_proveedor = new HashSet<recepcion_proveedor>();
            this.toma_fisica1 = new HashSet<toma_fisica>();
            this.permiso_empleado = new HashSet<permiso_empleado>();
            this.movimiento_bancario = new HashSet<movimiento_bancario>();
            this.toma_fisica2 = new HashSet<toma_fisica>();
            this.pedido_cliente = new HashSet<pedido_cliente>();
            this.plan_produccion = new HashSet<plan_produccion>();
            this.movimiento_presupuestaria = new HashSet<movimiento_presupuestaria>();
            this.pago_cash2 = new HashSet<pago_cash>();
            this.motivo_baja_activo = new HashSet<motivo_baja_activo>();
            this.orden_trabajo_mantenimiento = new HashSet<orden_trabajo_mantenimiento>();
            this.orden_despacho_cliente = new HashSet<orden_despacho_cliente>();
            this.factura_proveedor = new HashSet<factura_proveedor>();
            this.documento_gasto_importacion = new HashSet<documento_gasto_importacion>();
            this.movimiento_unidad_manejo = new HashSet<movimiento_unidad_manejo>();
            this.inventario_producto = new HashSet<inventario_producto>();
            this.pago_comision = new HashSet<pago_comision>();
        }
    
        public int id_documento { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int documento_base { get; set; }
        public Nullable<int> id_organizacion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public bool indicador_bloqueo_secuencia { get; set; }
        public bool indicador_consignacion { get; set; }
        public bool indicador_contabilizar { get; set; }
        public bool indicador_costo_estandar { get; set; }
        public bool indicador_documento_digital_requerido { get; set; }
        public bool indicador_documento_electronico { get; set; }
        public bool indicador_documento_exterior { get; set; }
        public bool indicador_documento_tributario { get; set; }
        public bool indicador_genera_costo { get; set; }
        public bool indicador_generar_documento_electronico { get; set; }
        public bool indicador_transferencia_ubicacion { get; set; }
        public string nombre { get; set; }
        public short operacion { get; set; }
        public bool predeterminado { get; set; }
        public string reporte { get; set; }
        public string reporte_2 { get; set; }
        public Nullable<int> id_documento_relacionado { get; set; }
        public Nullable<int> id_secuencia { get; set; }
        public Nullable<int> id_tipo_asiento { get; set; }
        public Nullable<int> id_tipo_asiento_2 { get; set; }
        public Nullable<int> id_tipo_comprobante { get; set; }
        public string reporte_envio_mail { get; set; }
        public bool indicador_genera_cxc { get; set; }
        public bool indicador_reembolso_gasto_venta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amortizacion> amortizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anticipo_cliente> anticipo_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anticipo_cliente> anticipo_cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anticipo_proveedor> anticipo_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anticipo_proveedor> anticipo_proveedor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asiento> asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<autorizacion_documento_SRI> autorizacion_documento_SRI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caja_chica> caja_chica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calidad> calidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carga_archivo> carga_archivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carta_porte_internacional_carretera> carta_porte_internacional_carretera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cass> cass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cobro> cobro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra_caja_chica> compra_caja_chica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<configuracion_credito_tributario> configuracion_credito_tributario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumo_agil_mantenimiento> consumo_agil_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumo_agil_mantenimiento> consumo_agil_mantenimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contrato_arrendamiento> contrato_arrendamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contrato_venta> contrato_venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<criterio_contabilizacion> criterio_contabilizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<criterio_distribucion> criterio_distribucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<depreciacion> depreciacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<despacho_cliente> despacho_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_vacacion> detalle_vacacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<devolucion_proveedor_consignacion> devolucion_proveedor_consignacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interfaz_contable_proceso> interfaz_contable_proceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guia_remision> guia_remision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_cash> pago_cash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_cliente> factura_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago> pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_proveedorSRI> factura_proveedorSRI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<liquidacion_anticipo_proveedor> liquidacion_anticipo_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_servicio_mantenimiento> orden_servicio_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_inventario> movimiento_inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipo_prestamo> tipo_prestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_partida_presupuestaria> movimiento_partida_presupuestaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoja_ruta> hoja_ruta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_rol> pago_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_empleado> pago_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<novedad_empleado> novedad_empleado { get; set; }
        public virtual secuencia secuencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento> documento1 { get; set; }
        public virtual documento documento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<precio_rango_cif> precio_rango_cif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_salida_material> orden_salida_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_fabricacion> orden_fabricacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_pago_proveedor> orden_pago_proveedor { get; set; }
        public virtual tipo_comprobanteSRI tipo_comprobanteSRI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_pago_proveedor> orden_pago_proveedor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_inventario> movimiento_inventario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_cash> pago_cash1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitud_compra> solicitud_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pre_devolucion_cliente> pre_devolucion_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prefactura_cliente> prefactura_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<redimir_puntos> redimir_puntos { get; set; }
        public virtual tipo_asiento tipo_asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<liquidacion_anticipo_cliente> liquidacion_anticipo_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_proveedor> pedido_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toma_fisica> toma_fisica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro_peso> registro_peso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recepcion_proveedor> recepcion_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toma_fisica> toma_fisica1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<permiso_empleado> permiso_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_bancario> movimiento_bancario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toma_fisica> toma_fisica2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_cliente> pedido_cliente { get; set; }
        public virtual tipo_asiento tipo_asiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plan_produccion> plan_produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_presupuestaria> movimiento_presupuestaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_cash> pago_cash2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<motivo_baja_activo> motivo_baja_activo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_trabajo_mantenimiento> orden_trabajo_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_despacho_cliente> orden_despacho_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_proveedor> factura_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento_gasto_importacion> documento_gasto_importacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_unidad_manejo> movimiento_unidad_manejo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_producto> inventario_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_comision> pago_comision { get; set; }
    }
}
