//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento_digitalizado_categoria_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documento_digitalizado_categoria_empresa()
        {
            this.detalle_documento_digitalizado = new HashSet<detalle_documento_digitalizado>();
        }
    
        public int id_documento_digitalizado_categoria_empresa { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool requerido { get; set; }
        public int id_categoriaEmpresa { get; set; }
        public int id_documento_digitalizado { get; set; }
    
        public virtual categoria_empresa categoria_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_documento_digitalizado> detalle_documento_digitalizado { get; set; }
        public virtual documento_digitalizado documento_digitalizado { get; set; }
    }
}
