//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class extracto_bancario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public extracto_bancario()
        {
            this.detalle_extracto_bancario = new HashSet<detalle_extracto_bancario>();
        }
    
        public int id_extracto_bancario { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public Nullable<int> id_interfaz_contable_proceso { get; set; }
    
        public virtual asiento asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_extracto_bancario> detalle_extracto_bancario { get; set; }
        public virtual interfaz_contable_proceso interfaz_contable_proceso { get; set; }
    }
}
