//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_clienteSRI
    {
        public int id_factura_clienteSRI { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int ambiente { get; set; }
        public Nullable<int> anio_refrendo { get; set; }
        public string autorizacion { get; set; }
        public Nullable<decimal> base_imponible_diferente_cero { get; set; }
        public Nullable<decimal> base_imponible_no_objeto_iva { get; set; }
        public Nullable<decimal> base_imponible_tarifa_cero { get; set; }
        public string clave_acceso { get; set; }
        public string codigo_forma_pago_sri { get; set; }
        public string codigo_unico { get; set; }
        public string correlativo_refrendo { get; set; }
        public string direccion_matriz { get; set; }
        public string direccion_sucursal { get; set; }
        public string distrito_refrendo { get; set; }
        public string documento_transporte_refrendo { get; set; }
        public string email { get; set; }
        public string establecimiento { get; set; }
        public int estado { get; set; }
        public Nullable<int> estado_documento_electronico { get; set; }
        public Nullable<System.DateTime> fecha_autorizacion { get; set; }
        public Nullable<System.DateTime> fecha_caducidad { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<System.DateTime> fecha_transaccion { get; set; }
        public Nullable<bool> generar_documento_electronico { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string identificacion_cliente { get; set; }
        public bool indicador_documento_electronico { get; set; }
        public bool indicador_saldo_inicial { get; set; }
        public bool ingreso_exterior_grabo_impuestos { get; set; }
        public string mensaje_sri { get; set; }
        public Nullable<decimal> monto_IRBPNR { get; set; }
        public Nullable<decimal> monto_ice { get; set; }
        public Nullable<decimal> monto_iva { get; set; }
        public string numero { get; set; }
        public string punto_emision { get; set; }
        public Nullable<int> refrendo { get; set; }
        public string regimen_refrendo { get; set; }
        public int tipo_emision { get; set; }
        public string tipo_ingreso_exterior { get; set; }
        public decimal total_subsidio { get; set; }
        public Nullable<decimal> valor_fob_comprobante_refrendo { get; set; }
        public Nullable<decimal> valor_fob_refrendo { get; set; }
        public decimal valor_impuesto_exportacion { get; set; }
        public Nullable<decimal> valor_retenido_fuente { get; set; }
        public Nullable<int> id_factura_cliente { get; set; }
        public Nullable<int> id_factura_proveedorSRI { get; set; }
        public Nullable<int> id_tipo_comprobante { get; set; }
        public Nullable<int> id_tipo_identificacion { get; set; }
    
        public virtual factura_cliente factura_cliente { get; set; }
        public virtual factura_proveedorSRI factura_proveedorSRI { get; set; }
        public virtual tipo_comprobanteSRI tipo_comprobanteSRI { get; set; }
        public virtual tipo_identificacion tipo_identificacion { get; set; }
    }
}
