//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flt_conductores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flt_conductores()
        {
            this.flt_despachos = new HashSet<flt_despachos>();
        }
    
        public int id_conductor { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string sucursal { get; set; }
        public int id_usuario { get; set; }
    
        public virtual user_login user_login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flt_despachos> flt_despachos { get; set; }
    }
}
