//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formacion_academica
    {
        public int id_formacion_academica { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<int> anio_desde { get; set; }
        public Nullable<int> anio_hasta { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<int> mes_desde { get; set; }
        public Nullable<int> mes_hasta { get; set; }
        public int id_empleado { get; set; }
        public int id_institucion_educativa { get; set; }
        public int id_nivel_instruccion { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual nivel_instruccion nivel_instruccion { get; set; }
        public virtual institucion_educativa institucion_educativa { get; set; }
    }
}
