//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class garante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public garante()
        {
            this.factura_cliente = new HashSet<factura_cliente>();
            this.factura_cliente1 = new HashSet<factura_cliente>();
            this.pedido_cliente = new HashSet<pedido_cliente>();
            this.pedido_cliente1 = new HashSet<pedido_cliente>();
        }
    
        public int id_garente { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public string email_respuesta { get; set; }
        public string extension1 { get; set; }
        public string extension2 { get; set; }
        public int id_organizacion { get; set; }
        public string mensajeria_instantanea1 { get; set; }
        public string mensajeria_instantanea2 { get; set; }
        public string nombre { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string telefono_respuesta { get; set; }
        public string identificacion { get; set; }
        public bool reportar { get; set; }
        public int tipo_garante { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public int id_ciudad { get; set; }
        public int id_tipo_identificacion { get; set; }
        public int id_ubicacion { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_cliente> factura_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_cliente> factura_cliente1 { get; set; }
        public virtual ubicacion ubicacion { get; set; }
        public virtual tipo_identificacion tipo_identificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_cliente> pedido_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_cliente> pedido_cliente1 { get; set; }
    }
}
