//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gasto_deducibleSRI
    {
        public int id_gasto_deducibleSRI { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int anio { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public decimal total_gastos_deducibles { get; set; }
        public Nullable<decimal> valor_alimentacion { get; set; }
        public Nullable<decimal> valor_Educacion { get; set; }
        public Nullable<decimal> valor_salud { get; set; }
        public Nullable<decimal> valor_vestimenta { get; set; }
        public Nullable<decimal> valor_vivienda { get; set; }
        public int id_empleado { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
