//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guia_aerea
    {
        public int id_guia_aerea { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string agent_code { get; set; }
        public string agents_reference_data { get; set; }
        public Nullable<int> airline_prefix { get; set; }
        public string awb_as_invoice_indicator { get; set; }
        public string awb_modular_number_check { get; set; }
        public string awb_number_modular_check { get; set; }
        public string awb_serial_number { get; set; }
        public string awb_use_indicator { get; set; }
        public string branch_office_indicator { get; set; }
        public string cca_dcm_number { get; set; }
        public Nullable<decimal> charges_due_agent { get; set; }
        public Nullable<int> charges_due_agent_pp { get; set; }
        public Nullable<decimal> charges_due_carrier { get; set; }
        public Nullable<decimal> charges_due_carrier_pp { get; set; }
        public Nullable<decimal> commission { get; set; }
        public string commission_indicator { get; set; }
        public Nullable<int> commission_percentage { get; set; }
        public string currency_code { get; set; }
        public Nullable<int> date_awb_acceptance { get; set; }
        public Nullable<int> date_awb_execution { get; set; }
        public Nullable<int> day { get; set; }
        public string destination { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string discount_indicato { get; set; }
        public Nullable<int> discount_indicator { get; set; }
        public string filler { get; set; }
        public string filler2 { get; set; }
        public string filler3 { get; set; }
        public string filler4 { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<int> late_indicator { get; set; }
        public Nullable<int> nora_sales_period { get; set; }
        public string origin { get; set; }
        public Nullable<decimal> other_charges_due_agent_cc { get; set; }
        public Nullable<decimal> other_charges_due_carrier_cc { get; set; }
        public string pp_cc_indicator1 { get; set; }
        public string pp_cc_indicator2 { get; set; }
        public string pp_cc_indicator3 { get; set; }
        public string pp_cc_indicator4 { get; set; }
        public string pp_cc_indicator5 { get; set; }
        public Nullable<decimal> rate_of_exchange { get; set; }
        public string reason_for_adjustment { get; set; }
        public string record_id { get; set; }
        public string reporting_indicator { get; set; }
        public string reserved_space { get; set; }
        public Nullable<int> sequence_number { get; set; }
        public Nullable<int> tax_due_agent { get; set; }
        public Nullable<int> tax_due_airline { get; set; }
        public string tax_due_airline_indicator { get; set; }
        public Nullable<int> taxes { get; set; }
        public Nullable<int> valuation_charge { get; set; }
        public Nullable<int> valuation_charge_cc { get; set; }
        public Nullable<int> valuation_charge_pp { get; set; }
        public string vat_indicator { get; set; }
        public Nullable<int> vat_on_awb_charges { get; set; }
        public Nullable<int> vat_on_commission { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<decimal> weight_charge { get; set; }
        public Nullable<decimal> weight_charge_cc { get; set; }
        public Nullable<decimal> weight_charge_pp { get; set; }
        public Nullable<int> weight_gross { get; set; }
        public string weight_indicator { get; set; }
        public Nullable<int> id_cass { get; set; }
    
        public virtual cass cass { get; set; }
    }
}
