//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historico_empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public historico_empleado()
        {
            this.detalle_finiquito_empleado = new HashSet<detalle_finiquito_empleado>();
            this.detalle_historico_empleado = new HashSet<detalle_historico_empleado>();
            this.pago_rol_empleado = new HashSet<pago_rol_empleado>();
            this.vacacion = new HashSet<vacacion>();
            this.permiso_empleado = new HashSet<permiso_empleado>();
        }
    
        public int id_historico_empleado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string contrato { get; set; }
        public string descripcion { get; set; }
        public int dias_fondo_reserva { get; set; }
        public Nullable<decimal> dias_vacaciones_finiquito { get; set; }
        public Nullable<int> estado_finiquito { get; set; }
        public Nullable<System.DateTime> fecha_finiquito { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_ingreso_terciarizado { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento_contrato { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_finiquito { get; set; }
        public string numero_finiquito { get; set; }
        public Nullable<decimal> saldo_prestamos { get; set; }
        public Nullable<decimal> valor_desahucio { get; set; }
        public Nullable<decimal> valor_remuneracion_decimo_tercero { get; set; }
        public Nullable<decimal> valor_remuneracion_vacacion { get; set; }
        public Nullable<decimal> valor_ultima_remuneracion { get; set; }
        public Nullable<int> id_asiento_finiquito { get; set; }
        public Nullable<int> id_causa_salida_empleado { get; set; }
        public int id_empleado { get; set; }
        public Nullable<int> id_pago_rol_empleado { get; set; }
        public Nullable<int> id_rubro_decimo_cuarto { get; set; }
        public Nullable<int> id_rubro_decimo_tercero { get; set; }
        public Nullable<int> id_rubro_fondo_reserva { get; set; }
    
        public virtual asiento asiento { get; set; }
        public virtual causa_salida_empleado causa_salida_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_finiquito_empleado> detalle_finiquito_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_historico_empleado> detalle_historico_empleado { get; set; }
        public virtual empleado empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_rol_empleado> pago_rol_empleado { get; set; }
        public virtual rubro rubro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vacacion> vacacion { get; set; }
        public virtual rubro rubro1 { get; set; }
        public virtual rubro rubro2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<permiso_empleado> permiso_empleado { get; set; }
        public virtual pago_rol_empleado pago_rol_empleado1 { get; set; }
    }
}
