//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historico_activo_fijo
    {
        public int id_historico_activo_fijo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public System.DateTime fecha_movimiento { get; set; }
        public Nullable<int> id_activo_padre_final { get; set; }
        public Nullable<int> id_activo_padre_inicial { get; set; }
        public Nullable<int> id_activo_manipulado { get; set; }
    
        public virtual activo_fijo activo_fijo { get; set; }
        public virtual activo_fijo activo_fijo1 { get; set; }
        public virtual activo_fijo activo_fijo2 { get; set; }
    }
}
