//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario_empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public horario_empleado()
        {
            this.empleado = new HashSet<empleado>();
            this.plan_personalizado_horario_empleado = new HashSet<plan_personalizado_horario_empleado>();
        }
    
        public int id_horario_empleado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<bool> indicador_dia_descanso0 { get; set; }
        public Nullable<bool> indicador_dia_descanso1 { get; set; }
        public Nullable<bool> indicador_dia_descanso2 { get; set; }
        public Nullable<bool> indicador_dia_descanso3 { get; set; }
        public Nullable<bool> indicador_dia_descanso4 { get; set; }
        public Nullable<bool> indicador_dia_descanso5 { get; set; }
        public Nullable<bool> indicador_dia_descanso6 { get; set; }
        public bool indicador_dia_opcional0 { get; set; }
        public bool indicador_dia_opcional1 { get; set; }
        public bool indicador_dia_opcional2 { get; set; }
        public bool indicador_dia_opcional3 { get; set; }
        public bool indicador_dia_opcional4 { get; set; }
        public bool indicador_dia_opcional5 { get; set; }
        public bool indicador_dia_opcional6 { get; set; }
        public bool indicador_horario_complementario0 { get; set; }
        public bool indicador_horario_complementario1 { get; set; }
        public bool indicador_horario_complementario2 { get; set; }
        public bool indicador_horario_complementario3 { get; set; }
        public bool indicador_horario_complementario4 { get; set; }
        public bool indicador_horario_complementario5 { get; set; }
        public bool indicador_horario_complementario6 { get; set; }
        public bool indicador_rotativo { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
        public Nullable<int> id_turno_0 { get; set; }
        public Nullable<int> id_turno_1 { get; set; }
        public Nullable<int> id_turno_2 { get; set; }
        public Nullable<int> id_turno_3 { get; set; }
        public Nullable<int> id_turno_4 { get; set; }
        public Nullable<int> id_turno_5 { get; set; }
        public Nullable<int> id_turno_6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual turno turno { get; set; }
        public virtual turno turno1 { get; set; }
        public virtual turno turno2 { get; set; }
        public virtual turno turno3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plan_personalizado_horario_empleado> plan_personalizado_horario_empleado { get; set; }
        public virtual turno turno4 { get; set; }
        public virtual turno turno5 { get; set; }
        public virtual turno turno6 { get; set; }
    }
}
