//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class impuesto_producto_factura_proveedor
    {
        public int id_impuesto_producto_factura_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<decimal> porcentaje_descuento_impuesto { get; set; }
        public Nullable<decimal> porcentaje_impuesto { get; set; }
        public Nullable<int> id_detalle_factura_proveedor { get; set; }
        public Nullable<int> id_impuesto { get; set; }
    
        public virtual detalle_factura_proveedor detalle_factura_proveedor { get; set; }
        public virtual impuesto impuesto { get; set; }
    }
}
