//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventario_producto()
        {
            this.detalle_pre_devolucion_cliente = new HashSet<detalle_pre_devolucion_cliente>();
            this.inventario_producto1 = new HashSet<inventario_producto>();
            this.inventario_producto11 = new HashSet<inventario_producto>();
            this.serie_inventario_producto = new HashSet<serie_inventario_producto>();
            this.inventario_producto12 = new HashSet<inventario_producto>();
        }
    
        public int id_inventario_producto { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public decimal cantidad { get; set; }
        public decimal cantidad_documento { get; set; }
        public Nullable<decimal> costo { get; set; }
        public decimal costo_depreciaciones { get; set; }
        public decimal costo_diferencia_importacion { get; set; }
        public decimal costo_indirectos { get; set; }
        public decimal costo_mano_de_obra { get; set; }
        public decimal costo_materiales { get; set; }
        public string cuenta1 { get; set; }
        public string cuenta2 { get; set; }
        public string descripcion { get; set; }
        public string descripcion2 { get; set; }
        public decimal diferencia { get; set; }
        public Nullable<int> documento_base { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora_creacion { get; set; }
        public int id_organizacion { get; set; }
        public Nullable<int> id_origen { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_anulacion { get; set; }
        public bool indicador_genera_costo { get; set; }
        public bool indicador_transferencia { get; set; }
        public Nullable<bool> indicador_transformacion { get; set; }
        public string nombre_fiscal_empresa { get; set; }
        public string numero_documento { get; set; }
        public int operacion { get; set; }
        public int orden { get; set; }
        public Nullable<int> ordigen_planificacion_produccion { get; set; }
        public Nullable<decimal> peso { get; set; }
        public string unidad_documento { get; set; }
        public Nullable<int> id_bodega { get; set; }
        public Nullable<int> id_detalle_despacho_cliente { get; set; }
        public Nullable<int> id_detalle_despacho_cliente_ajuste { get; set; }
        public Nullable<int> id_detalle_devolucion_cliente { get; set; }
        public Nullable<int> id_detalle_devolucion_proveedor { get; set; }
        public Nullable<int> id_detalle_devolucion_proveedor_consignacion { get; set; }
        public Nullable<int> id_detalle_movimiento_inventario { get; set; }
        public Nullable<int> id_detalle_movimiento_inventario_ajuste { get; set; }
        public Nullable<int> id_detalle_recepcion_proveedor { get; set; }
        public Nullable<int> id_detalle_recepcion_proveedor_ajuste { get; set; }
        public int id_documento { get; set; }
        public Nullable<int> id_inventario_producto_origen_anulacion { get; set; }
        public Nullable<int> id_inventario_producto_transferencia { get; set; }
        public Nullable<int> id_inventario_producto_transformacion { get; set; }
        public Nullable<int> id_lote { get; set; }
        public Nullable<int> id_orden_fabricacion { get; set; }
        public int id_producto { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public decimal costo_depreciaciones_estandar { get; set; }
        public decimal costo_estandar { get; set; }
        public decimal costo_indirectos_estandar { get; set; }
        public decimal costo_mano_de_obra_estandar { get; set; }
        public decimal costo_materiales_estandar { get; set; }
    
        public virtual bodega bodega { get; set; }
        public virtual detalle_despacho_cliente detalle_despacho_cliente { get; set; }
        public virtual detalle_despacho_cliente detalle_despacho_cliente1 { get; set; }
        public virtual detalle_devolucion_proveedor_consignacion detalle_devolucion_proveedor_consignacion { get; set; }
        public virtual detalle_factura_cliente detalle_factura_cliente { get; set; }
        public virtual detalle_factura_proveedor detalle_factura_proveedor { get; set; }
        public virtual detalle_movimiento_inventario detalle_movimiento_inventario { get; set; }
        public virtual detalle_movimiento_inventario detalle_movimiento_inventario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pre_devolucion_cliente> detalle_pre_devolucion_cliente { get; set; }
        public virtual detalle_recepcion_proveedor detalle_recepcion_proveedor { get; set; }
        public virtual detalle_recepcion_proveedor detalle_recepcion_proveedor1 { get; set; }
        public virtual dimension_contable dimension_contable { get; set; }
        public virtual documento documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_producto> inventario_producto1 { get; set; }
        public virtual inventario_producto inventario_producto2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_producto> inventario_producto11 { get; set; }
        public virtual inventario_producto inventario_producto3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serie_inventario_producto> serie_inventario_producto { get; set; }
        public virtual producto producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_producto> inventario_producto12 { get; set; }
        public virtual inventario_producto inventario_producto4 { get; set; }
        public virtual orden_fabricacion orden_fabricacion { get; set; }
        public virtual lote lote { get; set; }
    }
}
