//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invt_productos_stock
    {
        public string empresa { get; set; }
        public string codigo_producto_empresa { get; set; }
        public string grupo { get; set; }
        public string nombre_producto { get; set; }
        public Nullable<decimal> stock { get; set; }
    }
}
