//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lote()
        {
            this.detalle_calidad = new HashSet<detalle_calidad>();
            this.detalle_consumo_agil_mantenimiento = new HashSet<detalle_consumo_agil_mantenimiento>();
            this.detalle_despacho_cliente_material = new HashSet<detalle_despacho_cliente_material>();
            this.detalle_devolucion_proveedor_consignacion = new HashSet<detalle_devolucion_proveedor_consignacion>();
            this.detalle_factura_cliente = new HashSet<detalle_factura_cliente>();
            this.detalle_movimiento_inventario = new HashSet<detalle_movimiento_inventario>();
            this.detalle_orden_despacho_cliente = new HashSet<detalle_orden_despacho_cliente>();
            this.detalle_orden_salida_material = new HashSet<detalle_orden_salida_material>();
            this.detalle_plan_produccion = new HashSet<detalle_plan_produccion>();
            this.detalle_pre_devolucion_cliente = new HashSet<detalle_pre_devolucion_cliente>();
            this.detalle_recepcion_proveedor = new HashSet<detalle_recepcion_proveedor>();
            this.detalle_registro_peso_lote = new HashSet<detalle_registro_peso_lote>();
            this.detalle_toma_fisica = new HashSet<detalle_toma_fisica>();
            this.historico_calidad_orden_fabricacion = new HashSet<historico_calidad_orden_fabricacion>();
            this.inventario_producto = new HashSet<inventario_producto>();
            this.orden_fabricacion = new HashSet<orden_fabricacion>();
            this.movimiento_inventario = new HashSet<movimiento_inventario>();
            this.registro_peso = new HashSet<registro_peso>();
            this.saldo_producto_lote = new HashSet<saldo_producto_lote>();
        }
    
        public int id_lote { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<bool> activo { get; set; }
        public string codigo { get; set; }
        public System.DateTime fecha_caducidad { get; set; }
        public Nullable<System.DateTime> fecha_fabricacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_movimiento_interno { get; set; }
        public string pdf { get; set; }
        public string serie { get; set; }
        public Nullable<int> id_atributo_1 { get; set; }
        public Nullable<int> id_atributo_10 { get; set; }
        public Nullable<int> id_atributo_2 { get; set; }
        public Nullable<int> id_atributo_3 { get; set; }
        public Nullable<int> id_atributo_4 { get; set; }
        public Nullable<int> id_atributo_5 { get; set; }
        public Nullable<int> id_atributo_6 { get; set; }
        public Nullable<int> id_atributo_7 { get; set; }
        public Nullable<int> id_atributo_8 { get; set; }
        public Nullable<int> id_atributo_9 { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public int id_producto { get; set; }
        public Nullable<int> id_valor_atributo_1 { get; set; }
        public Nullable<int> id_valor_atributo_10 { get; set; }
        public Nullable<int> id_valor_atributo_2 { get; set; }
        public Nullable<int> id_valor_atributo_3 { get; set; }
        public Nullable<int> id_valor_atributo_4 { get; set; }
        public Nullable<int> id_valor_atributo_5 { get; set; }
        public Nullable<int> id_valor_atributo_6 { get; set; }
        public Nullable<int> id_valor_atributo_7 { get; set; }
        public Nullable<int> id_valor_atributo_8 { get; set; }
        public Nullable<int> id_valor_atributo_9 { get; set; }
    
        public virtual atributo atributo { get; set; }
        public virtual atributo atributo1 { get; set; }
        public virtual atributo atributo2 { get; set; }
        public virtual atributo atributo3 { get; set; }
        public virtual atributo atributo4 { get; set; }
        public virtual atributo atributo5 { get; set; }
        public virtual atributo atributo6 { get; set; }
        public virtual atributo atributo7 { get; set; }
        public virtual atributo atributo8 { get; set; }
        public virtual atributo atributo9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_calidad> detalle_calidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_consumo_agil_mantenimiento> detalle_consumo_agil_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_despacho_cliente_material> detalle_despacho_cliente_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_devolucion_proveedor_consignacion> detalle_devolucion_proveedor_consignacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_cliente> detalle_factura_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_movimiento_inventario> detalle_movimiento_inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_orden_despacho_cliente> detalle_orden_despacho_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_orden_salida_material> detalle_orden_salida_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_produccion> detalle_plan_produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pre_devolucion_cliente> detalle_pre_devolucion_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_recepcion_proveedor> detalle_recepcion_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_registro_peso_lote> detalle_registro_peso_lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_toma_fisica> detalle_toma_fisica { get; set; }
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historico_calidad_orden_fabricacion> historico_calidad_orden_fabricacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_producto> inventario_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_fabricacion> orden_fabricacion { get; set; }
        public virtual valor_atributo valor_atributo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_inventario> movimiento_inventario { get; set; }
        public virtual valor_atributo valor_atributo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro_peso> registro_peso { get; set; }
        public virtual valor_atributo valor_atributo2 { get; set; }
        public virtual valor_atributo valor_atributo3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saldo_producto_lote> saldo_producto_lote { get; set; }
        public virtual producto producto { get; set; }
        public virtual valor_atributo valor_atributo4 { get; set; }
        public virtual valor_atributo valor_atributo5 { get; set; }
        public virtual valor_atributo valor_atributo6 { get; set; }
        public virtual valor_atributo valor_atributo7 { get; set; }
        public virtual valor_atributo valor_atributo8 { get; set; }
        public virtual valor_atributo valor_atributo9 { get; set; }
    }
}
