//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class material_orden_trabajo_mantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material_orden_trabajo_mantenimiento()
        {
            this.actividad_material_orden_trabajo_mantenimiento = new HashSet<actividad_material_orden_trabajo_mantenimiento>();
            this.detalle_movimiento_inventario = new HashSet<detalle_movimiento_inventario>();
        }
    
        public int id_material_orden_trabajo_mantenimiento { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public decimal cantidad_despachada { get; set; }
        public decimal cantidad_devuelta { get; set; }
        public decimal cantidad_requerida { get; set; }
        public Nullable<int> id_organizacion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public bool indicador_garantia { get; set; }
        public Nullable<decimal> precioMaterial { get; set; }
        public int id_material { get; set; }
        public int id_orden_trabajo_mantenimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividad_material_orden_trabajo_mantenimiento> actividad_material_orden_trabajo_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_movimiento_inventario> detalle_movimiento_inventario { get; set; }
        public virtual orden_trabajo_mantenimiento orden_trabajo_mantenimiento { get; set; }
        public virtual producto producto { get; set; }
    }
}
