//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public moneda()
        {
            this.detalle_factura_proveedor_importacion_gasto = new HashSet<detalle_factura_proveedor_importacion_gasto>();
            this.factura_proveedor_gasto_importacion = new HashSet<factura_proveedor_gasto_importacion>();
            this.factura_proveedor_importacion = new HashSet<factura_proveedor_importacion>();
            this.lista_precios = new HashSet<lista_precios>();
        }
    
        public int id_moneda { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura_proveedor_importacion_gasto> detalle_factura_proveedor_importacion_gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_proveedor_gasto_importacion> factura_proveedor_gasto_importacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_proveedor_importacion> factura_proveedor_importacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lista_precios> lista_precios { get; set; }
    }
}
