//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento_unidad_manejo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimiento_unidad_manejo()
        {
            this.detalle_movimiento_unidad_manejo = new HashSet<detalle_movimiento_unidad_manejo>();
        }
    
        public int id_movimiento_unidad_manejo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public int estado { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public int id_organizacion { get; set; }
        public Nullable<bool> indicador_ajuste_unidad_manejo { get; set; }
        public string numero { get; set; }
        public int id_documento { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_motivo_ajuste_unidad_manejo { get; set; }
        public Nullable<int> id_subempresa { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<int> id_transportista { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_movimiento_unidad_manejo> detalle_movimiento_unidad_manejo { get; set; }
        public virtual documento documento { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual motivo_ajuste_unidad_manejo motivo_ajuste_unidad_manejo { get; set; }
        public virtual subempresa subempresa { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual transportista transportista { get; set; }
    }
}
