//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class noti_noticias_principal
    {
        public int id_noticia { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string ruta_imagen { get; set; }
        public string ruta_video { get; set; }
        public bool anulada { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
