//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class novedad_empleado
    {
        public int id_novedad_empleado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_desde { get; set; }
        public string fichero { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string numero { get; set; }
        public Nullable<int> id_documento { get; set; }
        public int id_empleado { get; set; }
        public int id_motivo_novedad { get; set; }
    
        public virtual documento documento { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual motivo_novedad motivo_novedad { get; set; }
    }
}
