//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_despacho_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orden_despacho_cliente()
        {
            this.despacho_cliente = new HashSet<despacho_cliente>();
            this.detalle_orden_despacho_cliente = new HashSet<detalle_orden_despacho_cliente>();
            this.movimiento_inventario = new HashSet<movimiento_inventario>();
        }
    
        public int id_orden_despacho_cliente { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public int estado { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_organizacion { get; set; }
        public string numero { get; set; }
        public int id_documento { get; set; }
        public Nullable<int> id_pedido_cliente { get; set; }
        public int id_sucursal { get; set; }
        public int id_tipo_orden_despacho { get; set; }
        public Nullable<int> id_tipo_presentacion_producto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<despacho_cliente> despacho_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_orden_despacho_cliente> detalle_orden_despacho_cliente { get; set; }
        public virtual documento documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_inventario> movimiento_inventario { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual pedido_cliente pedido_cliente { get; set; }
        public virtual tipo_presentacion_producto tipo_presentacion_producto { get; set; }
        public virtual tipo_orden_despacho tipo_orden_despacho { get; set; }
    }
}
