//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago_empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pago_empleado()
        {
            this.pago_rol_empleado = new HashSet<pago_rol_empleado>();
        }
    
        public int id_pago_empleado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string apellidos { get; set; }
        public string descripcion { get; set; }
        public int estado { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_contabilizar { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string identificacion { get; set; }
        public string nombres { get; set; }
        public string numero { get; set; }
        public string pdf { get; set; }
        public decimal valor { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public int id_cuenta_bancaria_organizacion { get; set; }
        public int id_documento { get; set; }
        public int id_forma_pago { get; set; }
        public int id_pago_rol { get; set; }
    
        public virtual asiento asiento { get; set; }
        public virtual cuenta_bancaria_organizacion cuenta_bancaria_organizacion { get; set; }
        public virtual documento documento { get; set; }
        public virtual forma_pago forma_pago { get; set; }
        public virtual pago_rol pago_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_rol_empleado> pago_rol_empleado { get; set; }
    }
}
