//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago_rol_empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pago_rol_empleado()
        {
            this.detalle_pago_cuota_prestamo = new HashSet<detalle_pago_cuota_prestamo>();
            this.detalle_prestamo = new HashSet<detalle_prestamo>();
            this.historico_empleado1 = new HashSet<historico_empleado>();
            this.pago_rol_empleado_rubro = new HashSet<pago_rol_empleado_rubro>();
        }
    
        public int id_pago_rol_empleado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<decimal> base_imponible_iees { get; set; }
        public Nullable<decimal> base_imponible_impuesto_renta { get; set; }
        public int dias_falta { get; set; }
        public Nullable<int> dias_proceso { get; set; }
        public Nullable<int> dias_trabajados { get; set; }
        public string documento_referencia { get; set; }
        public string errores_calculo { get; set; }
        public Nullable<System.DateTime> fecha_ingreso_empleado { get; set; }
        public Nullable<System.DateTime> fecha_salida_empleado { get; set; }
        public int horas_no_trabajadas_jornada_reducida { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<bool> indicador_aprobado { get; set; }
        public Nullable<bool> indicador_cobrado { get; set; }
        public decimal salario_asignado { get; set; }
        public Nullable<decimal> valor_a_pagar { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public Nullable<int> id_centro_costo { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public int id_empleado { get; set; }
        public Nullable<int> id_historico_empleado { get; set; }
        public Nullable<int> id_pago_cash { get; set; }
        public Nullable<int> id_pago_empleado { get; set; }
        public Nullable<int> id_pago_rol { get; set; }
    
        public virtual asiento asiento { get; set; }
        public virtual departamento departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pago_cuota_prestamo> detalle_pago_cuota_prestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_prestamo> detalle_prestamo { get; set; }
        public virtual dimension_contable dimension_contable { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual historico_empleado historico_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historico_empleado> historico_empleado1 { get; set; }
        public virtual pago_cash pago_cash { get; set; }
        public virtual pago_empleado pago_empleado { get; set; }
        public virtual pago_rol pago_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_rol_empleado_rubro> pago_rol_empleado_rubro { get; set; }
    }
}
