//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago_rol_empleado_rubro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pago_rol_empleado_rubro()
        {
            this.pago_rol_empleado_rubro1 = new HashSet<pago_rol_empleado_rubro>();
        }
    
        public int id_pago_rol_empleado_rubro { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string detalle_provision_liquidada_finiquito { get; set; }
        public string detalle_vacacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string ids_detalle_vacacion { get; set; }
        public bool indicador_automatico { get; set; }
        public Nullable<bool> indicador_calculo_IESS { get; set; }
        public bool indicador_calculo_impuesto_renta { get; set; }
        public Nullable<bool> indicador_impresion_sobre { get; set; }
        public Nullable<bool> indicador_manual { get; set; }
        public bool indicador_no_procesado { get; set; }
        public Nullable<bool> indicador_provision { get; set; }
        public Nullable<bool> indicador_tiempo { get; set; }
        public string numero_cuotas { get; set; }
        public Nullable<decimal> tiempo { get; set; }
        public Nullable<decimal> tiempo2 { get; set; }
        public Nullable<decimal> tiempo3 { get; set; }
        public Nullable<decimal> tiempo_por_liquidar { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> valor2 { get; set; }
        public Nullable<decimal> valor3 { get; set; }
        public Nullable<decimal> valor_por_liquidar { get; set; }
        public Nullable<int> id_pago_rol_empleado { get; set; }
        public Nullable<int> id_pago_rol_empleado_padre { get; set; }
        public int id_rubro { get; set; }
    
        public virtual pago_rol_empleado pago_rol_empleado { get; set; }
        public virtual rubro rubro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_rol_empleado_rubro> pago_rol_empleado_rubro1 { get; set; }
        public virtual pago_rol_empleado_rubro pago_rol_empleado_rubro2 { get; set; }
    }
}
