//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public periodo()
        {
            this.asiento = new HashSet<asiento>();
        }
    
        public int id_periodo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_desde { get; set; }
        public System.DateTime fecha_hasta { get; set; }
        public Nullable<int> id_organizacion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public bool indicador_cierre_activos_fijos { get; set; }
        public bool indicador_cierre_cobros { get; set; }
        public bool indicador_cierre_compras { get; set; }
        public bool indicador_cierre_contabilidad { get; set; }
        public bool indicador_cierre_inventario { get; set; }
        public bool indicador_cierre_nomina { get; set; }
        public bool indicador_cierre_pagos { get; set; }
        public bool indicador_cierre_presupuesto { get; set; }
        public bool indicador_cierre_produccion { get; set; }
        public bool indicador_cierre_ventas { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_ejercicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asiento> asiento { get; set; }
        public virtual ejercicio ejercicio { get; set; }
    }
}
