//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pre_devolucion_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pre_devolucion_cliente()
        {
            this.detalle_pre_devolucion_cliente = new HashSet<detalle_pre_devolucion_cliente>();
        }
    
        public int id_pre_devolucion_cliente { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string codigo_movil { get; set; }
        public int estado { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<int> id_factura_cliente_padre { get; set; }
        public int id_organizacion { get; set; }
        public string nota { get; set; }
        public string nota_transportista { get; set; }
        public string numero { get; set; }
        public string referencia8 { get; set; }
        public decimal total { get; set; }
        public Nullable<int> id_documento { get; set; }
        public int id_empresa { get; set; }
        public Nullable<int> id_motivo_nota_credito_cliente { get; set; }
        public Nullable<int> id_recepcion_devolucion_transportista { get; set; }
        public Nullable<int> id_subempresa { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<int> id_transportista { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pre_devolucion_cliente> detalle_pre_devolucion_cliente { get; set; }
        public virtual documento documento { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual motivo_nota_credito_cliente motivo_nota_credito_cliente { get; set; }
        public virtual subempresa subempresa { get; set; }
        public virtual recepcion_devolucion_transportista recepcion_devolucion_transportista { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
