//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public presupuesto_compra()
        {
            this.detalle_presupuesto_compra = new HashSet<detalle_presupuesto_compra>();
            this.movimiento_partida_presupuestaria = new HashSet<movimiento_partida_presupuestaria>();
        }
    
        public int id_presupuesto_compra { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int anio { get; set; }
        public int estado { get; set; }
        public int id_organizacion { get; set; }
        public int tipo_presupuesto { get; set; }
        public int id_sucursal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_presupuesto_compra> detalle_presupuesto_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_partida_presupuestaria> movimiento_partida_presupuestaria { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
