//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_procesos_principal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pro_procesos_principal()
        {
            this.pro_alarmas = new HashSet<pro_alarmas>();
            this.pro_facturas = new HashSet<pro_facturas>();
            this.pro_ordenes_compra = new HashSet<pro_ordenes_compra>();
        }
    
        public int id_procesos { get; set; }
        public string empresa { get; set; }
        public string codigo_proceso { get; set; }
        public int resp_proceso { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string codigo_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public decimal valor_proceso { get; set; }
        public string representante { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> suma_oc { get; set; }
        public Nullable<decimal> suma_fact { get; set; }
        public bool cerrado { get; set; }
        public sbyte vae { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pro_alarmas> pro_alarmas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pro_facturas> pro_facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pro_ordenes_compra> pro_ordenes_compra { get; set; }
    }
}
