//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_ordenes_compra
    {
        public int id_ordenes_compra { get; set; }
        public string orden_compra { get; set; }
        public float valor_oc { get; set; }
        public int id_procesos { get; set; }
    
        public virtual pro_procesos_principal pro_procesos_principal { get; set; }
    }
}
