//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_atributo
    {
        public int id_producto_atributo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string valor { get; set; }
        public int id_atributo { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_valor_atributo { get; set; }
    
        public virtual atributo atributo { get; set; }
        public virtual producto producto { get; set; }
        public virtual valor_atributo valor_atributo { get; set; }
    }
}
