//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propina
    {
        public int id_propina { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public decimal valor { get; set; }
        public Nullable<int> id_pago_rol { get; set; }
        public Nullable<int> id_pago_rol_dias_trabajados { get; set; }
    
        public virtual pago_rol pago_rol { get; set; }
        public virtual pago_rol pago_rol1 { get; set; }
    }
}
