//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recepcion_proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recepcion_proveedor()
        {
            this.detalle_recepcion_proveedor = new HashSet<detalle_recepcion_proveedor>();
            this.devolucion_proveedor_consignacion = new HashSet<devolucion_proveedor_consignacion>();
            this.factura_proveedor = new HashSet<factura_proveedor>();
        }
    
        public int id_recepcion_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public string descripcion_anulacion { get; set; }
        public int estado { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_anulacion { get; set; }
        public Nullable<System.DateTime> fecha_contabilizacion { get; set; }
        public int id_organizacion { get; set; }
        public bool indicador_consignacion { get; set; }
        public Nullable<bool> indicador_tiene_recepcion_parcial { get; set; }
        public string numero { get; set; }
        public string numero_factura { get; set; }
        public string pdf { get; set; }
        public string referencia1 { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public int id_documento { get; set; }
        public int id_empresa { get; set; }
        public Nullable<int> id_pedido_proveedor { get; set; }
        public Nullable<int> id_persona_responsable { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public Nullable<int> id_registro_peso { get; set; }
        public int id_sucursal { get; set; }
    
        public virtual asiento asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_recepcion_proveedor> detalle_recepcion_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<devolucion_proveedor_consignacion> devolucion_proveedor_consignacion { get; set; }
        public virtual dimension_contable dimension_contable { get; set; }
        public virtual documento documento { get; set; }
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_proveedor> factura_proveedor { get; set; }
        public virtual pedido_proveedor pedido_proveedor { get; set; }
        public virtual registro_peso registro_peso { get; set; }
        public virtual responsable_salida_mercaderia responsable_salida_mercaderia { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
