//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_movil
    {
        public int id_registro_movil { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string codigo_movil { get; set; }
        public int documento_base { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string nota { get; set; }
        public string numero_as2 { get; set; }
        public string usuario { get; set; }
    }
}
