//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_peso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registro_peso()
        {
            this.detalle_registro_peso = new HashSet<detalle_registro_peso>();
            this.detalle_registro_peso_lote = new HashSet<detalle_registro_peso_lote>();
            this.recepcion_proveedor = new HashSet<recepcion_proveedor>();
            this.variable_calidad_registro_peso = new HashSet<variable_calidad_registro_peso>();
        }
    
        public int id_registro_peso { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string carga_otros { get; set; }
        public string cargas_anteriores { get; set; }
        public string condiciones_empaque { get; set; }
        public Nullable<bool> control_calidad_finalizado { get; set; }
        public string descripcion { get; set; }
        public string direccion { get; set; }
        public int estado { get; set; }
        public Nullable<int> estado_control_calidad { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_caducidad { get; set; }
        public Nullable<System.DateTime> fecha_elaboracion { get; set; }
        public Nullable<System.DateTime> fecha_entrada { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_liquidado_flete { get; set; }
        public Nullable<bool> liberado_castigo { get; set; }
        public string nombre_chofer { get; set; }
        public string numero { get; set; }
        public string numero_guia_remision { get; set; }
        public string numero_registro_sanitario { get; set; }
        public string observacion { get; set; }
        public string observacion_calidad { get; set; }
        public Nullable<decimal> peso_destare_total { get; set; }
        public Nullable<decimal> peso_destare_unidad { get; set; }
        public Nullable<decimal> peso_entrada { get; set; }
        public Nullable<decimal> peso_neto { get; set; }
        public Nullable<decimal> peso_referencia { get; set; }
        public Nullable<decimal> peso_salida { get; set; }
        public string placa_vehiculo { get; set; }
        public string presentacion { get; set; }
        public int tipo_registro_peso { get; set; }
        public string tipo_registro_sanitario { get; set; }
        public Nullable<int> id_bodega { get; set; }
        public Nullable<int> id_bodega_liberar { get; set; }
        public int id_chofer { get; set; }
        public Nullable<int> id_despacho_cliente { get; set; }
        public Nullable<int> id_detalle_factura_proveedor { get; set; }
        public Nullable<int> id_detalle_pedido_proveedor { get; set; }
        public Nullable<int> id_detalle_pedido_proveedor_original { get; set; }
        public Nullable<int> id__detalle_transferencia_bodega { get; set; }
        public Nullable<int> id_devolucion_cliente { get; set; }
        public Nullable<int> id_dispositivo { get; set; }
        public int id_documento { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_lote { get; set; }
        public Nullable<int> id_motivo_castigo_calidad { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_ruta { get; set; }
        public Nullable<int> id_transferencia_bodega { get; set; }
        public int id_transportista { get; set; }
        public int id_vehiculo { get; set; }
    
        public virtual bodega bodega { get; set; }
        public virtual bodega bodega1 { get; set; }
        public virtual chofer chofer { get; set; }
        public virtual despacho_cliente despacho_cliente { get; set; }
        public virtual detalle_factura_proveedor detalle_factura_proveedor { get; set; }
        public virtual detalle_movimiento_inventario detalle_movimiento_inventario { get; set; }
        public virtual detalle_pedido_proveedor detalle_pedido_proveedor { get; set; }
        public virtual detalle_pedido_proveedor detalle_pedido_proveedor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_registro_peso> detalle_registro_peso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_registro_peso_lote> detalle_registro_peso_lote { get; set; }
        public virtual dispositivo dispositivo { get; set; }
        public virtual documento documento { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual factura_cliente factura_cliente { get; set; }
        public virtual lote lote { get; set; }
        public virtual motivo_castigo_calidad motivo_castigo_calidad { get; set; }
        public virtual movimiento_inventario movimiento_inventario { get; set; }
        public virtual producto producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recepcion_proveedor> recepcion_proveedor { get; set; }
        public virtual ruta ruta { get; set; }
        public virtual transportista transportista { get; set; }
        public virtual vehiculo vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<variable_calidad_registro_peso> variable_calidad_registro_peso { get; set; }
    }
}
