//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsable_orden_trabajo_mantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public responsable_orden_trabajo_mantenimiento()
        {
            this.actividad_responsable_orden_trabajo_mantenimiento = new HashSet<actividad_responsable_orden_trabajo_mantenimiento>();
        }
    
        public int id_responsable_orden_trabajo_mantenimiento { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public int id_orden_trabajo_mantenimiento { get; set; }
        public int id_persona_responsable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividad_responsable_orden_trabajo_mantenimiento> actividad_responsable_orden_trabajo_mantenimiento { get; set; }
        public virtual orden_trabajo_mantenimiento orden_trabajo_mantenimiento { get; set; }
        public virtual responsable_salida_mercaderia responsable_salida_mercaderia { get; set; }
    }
}
