//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_adelantos
    {
        public int id_adelantos { get; set; }
        public int id_usuario { get; set; }
        public string tipo { get; set; }
        public decimal valor { get; set; }
        public string motivo { get; set; }
        public bool autorizado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        public virtual user_login user_login { get; set; }
    }
}
