//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rubro_departamento_cuenta_contable
    {
        public int id_rubro_departamento_cuenta_contable { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<int> id_cuenta_contable { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<int> id_rubro { get; set; }
    
        public virtual cuenta_contable cuenta_contable { get; set; }
        public virtual departamento departamento { get; set; }
        public virtual rubro rubro { get; set; }
    }
}
