//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruta_fabricacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ruta_fabricacion()
        {
            this.detalle_componente_costo_distribucion = new HashSet<detalle_componente_costo_distribucion>();
            this.detalle_plan_maestro_produccion = new HashSet<detalle_plan_maestro_produccion>();
            this.detalle_plan_produccion = new HashSet<detalle_plan_produccion>();
            this.operacion_produccion = new HashSet<operacion_produccion>();
            this.orden_fabricacion = new HashSet<orden_fabricacion>();
            this.producto = new HashSet<producto>();
            this.producto_ruta_fabricacion_sucursal = new HashSet<producto_ruta_fabricacion_sucursal>();
        }
    
        public int id_ruta_fabricacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
        public Nullable<int> tipo_ciclo_produccion_enum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_componente_costo_distribucion> detalle_componente_costo_distribucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_maestro_produccion> detalle_plan_maestro_produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_produccion> detalle_plan_produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operacion_produccion> operacion_produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_fabricacion> orden_fabricacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_ruta_fabricacion_sucursal> producto_ruta_fabricacion_sucursal { get; set; }
    }
}
