//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ruta()
        {
            this.orden_salida_material = new HashSet<orden_salida_material>();
            this.pedido_cliente = new HashSet<pedido_cliente>();
            this.registro_peso = new HashSet<registro_peso>();
        }
    
        public int id_ruta { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int forma_pago_flete { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string ruta1 { get; set; }
        public decimal tarifa { get; set; }
        public int id_ciudad_destino { get; set; }
        public int id_ciudad_origen { get; set; }
        public Nullable<int> id_tipo_vehiculo { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual ciudad ciudad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_salida_material> orden_salida_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_cliente> pedido_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro_peso> registro_peso { get; set; }
        public virtual tipo_vehiculo tipo_vehiculo { get; set; }
    }
}
