//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saldo_unidad_manejo
    {
        public int id_saldo_unidad_manejo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int cantidad { get; set; }
        public int id_organizacion { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_subempresa { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<int> id_transportista { get; set; }
        public Nullable<int> id_unidad_manejo { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual subempresa subempresa { get; set; }
        public virtual unidad_manejo unidad_manejo { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual transportista transportista { get; set; }
    }
}
