//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud_compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public solicitud_compra()
        {
            this.cotizacion_proveedor = new HashSet<cotizacion_proveedor>();
            this.detalle_solicitud_compra = new HashSet<detalle_solicitud_compra>();
            this.pedido_proveedor = new HashSet<pedido_proveedor>();
        }
    
        public int id_solicitud_compra { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string descripcion { get; set; }
        public int estado { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_organizacion { get; set; }
        public Nullable<int> id_solicitud_compra_manager { get; set; }
        public string nombre_origen { get; set; }
        public string numero { get; set; }
        public string numero_consolidado_manager { get; set; }
        public string numero_manager { get; set; }
        public string numero_origen { get; set; }
        public string pdf { get; set; }
        public string usuario_aprobacion { get; set; }
        public string usuario_revision { get; set; }
        public Nullable<int> id_bodega { get; set; }
        public int id_documento { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public int id_sucursal { get; set; }
    
        public virtual bodega bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacion_proveedor> cotizacion_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_solicitud_compra> detalle_solicitud_compra { get; set; }
        public virtual documento documento { get; set; }
        public virtual empleado empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_proveedor> pedido_proveedor { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
