//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarea_produccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarea_produccion()
        {
            this.operacion_produccion = new HashSet<operacion_produccion>();
        }
    
        public int id_tarea_produccion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_organizacion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<bool> indicador_automatico { get; set; }
        public Nullable<bool> indicador_fijo { get; set; }
        public bool indicador_posconsumo { get; set; }
        public string nombre { get; set; }
        public decimal numero_maquinas { get; set; }
        public decimal numero_persona { get; set; }
        public bool predeterminado { get; set; }
        public int tiempo_entrega { get; set; }
        public int id_centro_trabajo { get; set; }
        public int id_maquina { get; set; }
        public int id_tarifa_operacion { get; set; }
    
        public virtual centro_trabajo centro_trabajo { get; set; }
        public virtual maquina maquina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operacion_produccion> operacion_produccion { get; set; }
        public virtual tarifa_operacion tarifa_operacion { get; set; }
    }
}
