//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta_credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarjeta_credito()
        {
            this.detalle_forma_cobro = new HashSet<detalle_forma_cobro>();
            this.version_comision = new HashSet<version_comision>();
        }
    
        public int id_tarjeta_credito { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public Nullable<int> columna_comision { get; set; }
        public Nullable<int> columna_fecha_cobro { get; set; }
        public Nullable<int> columna_fecha_deposito { get; set; }
        public Nullable<int> columna_iva { get; set; }
        public Nullable<int> columna_impuesto_renta { get; set; }
        public Nullable<int> columna_lote { get; set; }
        public Nullable<int> columna_valor_cobro { get; set; }
        public Nullable<int> columna_valor_pagado { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
        public Nullable<int> fila_inicial { get; set; }
        public string formato_fecha { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_deposito_individual { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
        public Nullable<int> red_pago { get; set; }
        public Nullable<int> id_banco { get; set; }
        public int id_cuenta_bancaria_organizacion { get; set; }
        public Nullable<int> id_cuenta_contable_iva_comision { get; set; }
        public Nullable<int> id_cuenta_contable_retentencion_fuente { get; set; }
        public Nullable<int> id_cuenta_contable_retentencion_iva { get; set; }
        public Nullable<int> id_tipo_tarjeta_credito { get; set; }
    
        public virtual banco banco { get; set; }
        public virtual cuenta_bancaria_organizacion cuenta_bancaria_organizacion { get; set; }
        public virtual cuenta_contable cuenta_contable { get; set; }
        public virtual cuenta_contable cuenta_contable1 { get; set; }
        public virtual cuenta_contable cuenta_contable2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_forma_cobro> detalle_forma_cobro { get; set; }
        public virtual tipo_tarjeta_credito tipo_tarjeta_credito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<version_comision> version_comision { get; set; }
    }
}
