//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tckt_subcategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tckt_subcategoria()
        {
            this.tckt_ticket_principal = new HashSet<tckt_ticket_principal>();
        }
    
        public int id_subcategoria { get; set; }
        public string nombre_subcat { get; set; }
        public int id_categoria { get; set; }
    
        public virtual tckt_categoria tckt_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tckt_ticket_principal> tckt_ticket_principal { get; set; }
    }
}
