//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ticket()
        {
            this.detalle_ticket = new HashSet<detalle_ticket>();
        }
    
        public int id_ticket { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<decimal> yq_cero { get; set; }
        public Nullable<decimal> yq_diferente_cero { get; set; }
        public string aerolinea { get; set; }
        public Nullable<decimal> anticipo { get; set; }
        public Nullable<decimal> bruto { get; set; }
        public string codigo_agente { get; set; }
        public string codigo_de_servicio { get; set; }
        public string codigo_disenio_ticket { get; set; }
        public Nullable<decimal> comision { get; set; }
        public Nullable<decimal> credito { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> diferencia { get; set; }
        public Nullable<decimal> e2 { get; set; }
        public Nullable<decimal> ed { get; set; }
        public string emisor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string fecha_computador { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<System.DateTime> fecha_reporte { get; set; }
        public Nullable<System.DateTime> fecha_viaje { get; set; }
        public string forma_pago { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string identificacion_tributaria { get; set; }
        public Nullable<decimal> impuesto_extranjero { get; set; }
        public Nullable<bool> indicador_contabilizado { get; set; }
        public Nullable<bool> indicador_ticket_credito { get; set; }
        public Nullable<bool> is_credito { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> iva_comision { get; set; }
        public string moneda { get; set; }
        public Nullable<decimal> neto { get; set; }
        public string numero { get; set; }
        public string numero_documento_relacionado { get; set; }
        public string numero_periodo { get; set; }
        public string observaciones { get; set; }
        public string operacion { get; set; }
        public string original_conjuncion { get; set; }
        public string pasajero { get; set; }
        public Nullable<decimal> penalty { get; set; }
        public Nullable<System.DateTime> periodo { get; set; }
        public string periodo_bsp { get; set; }
        public Nullable<decimal> por_comision { get; set; }
        public Nullable<decimal> qb { get; set; }
        public Nullable<decimal> qi { get; set; }
        public string record { get; set; }
        public string referencia { get; set; }
        public Nullable<decimal> retencionFte { get; set; }
        public Nullable<decimal> retencionIca { get; set; }
        public Nullable<decimal> retencionIvaCom { get; set; }
        public string ruta { get; set; }
        public Nullable<decimal> tarifa { get; set; }
        public Nullable<decimal> tarifa_cero { get; set; }
        public Nullable<decimal> tarifa_diferente_cero { get; set; }
        public Nullable<decimal> tarifa_moneda { get; set; }
        public Nullable<decimal> tarifa_preliminar { get; set; }
        public Nullable<decimal> tarjeta { get; set; }
        public string ticketCnj { get; set; }
        public string tipo { get; set; }
        public string tipo_de_documento { get; set; }
        public string tipo_tarjeta_credito { get; set; }
        public string tipo_transaccion { get; set; }
        public string usuario { get; set; }
        public string vale { get; set; }
        public string valex { get; set; }
        public Nullable<decimal> valor_forma_pago { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public Nullable<decimal> valor_total_preliminar { get; set; }
        public Nullable<decimal> wt { get; set; }
        public Nullable<decimal> yq { get; set; }
        public Nullable<decimal> yr { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public Nullable<int> id_bsp { get; set; }
        public Nullable<int> id_punto_venta { get; set; }
    
        public virtual asiento asiento { get; set; }
        public virtual carga_archivo carga_archivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ticket> detalle_ticket { get; set; }
        public virtual punto_de_venta punto_de_venta { get; set; }
    }
}
