//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_contacto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipo_contacto()
        {
            this.contacto = new HashSet<contacto>();
        }
    
        public int id_tipo_contacto { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_crm { get; set; }
        public bool indicador_elaboracion_solicitud_compra { get; set; }
        public bool indicador_nomina { get; set; }
        public bool indicador_notificar_devolucion_proveedor { get; set; }
        public bool indicador_notificar_factura { get; set; }
        public bool indicador_notificar_guia_remision { get; set; }
        public bool indicador_notificar_importacion { get; set; }
        public bool indicador_notificar_nota_credito { get; set; }
        public bool indicador_notificar_nota_debito { get; set; }
        public bool indicador_notificar_orden_servicio { get; set; }
        public bool indicador_notificar_pago_proveedor { get; set; }
        public bool indicador_notificar_pedido_cliente { get; set; }
        public bool indicador_notificar_pedido_proveedor { get; set; }
        public bool indicador_notificar_requisicion { get; set; }
        public bool indicador_notificar_retencion { get; set; }
        public bool indicador_notificar_solicitud_compra { get; set; }
        public bool indicador_notificar_vencimiento_factura_cliente { get; set; }
        public bool indicador_recepcion_proveedor { get; set; }
        public bool indicador_transferencia_entre_bodegas { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
        public string texto_cuerpo_correo_devolucion_proveedor_consignacion { get; set; }
        public string texto_cuerpo_correo_elaboracion_solicitud_compra { get; set; }
        public string texto_cuerpo_correo_factura { get; set; }
        public string texto_cuerpo_correo_guia_remision { get; set; }
        public string texto_cuerpo_correo_importaciones { get; set; }
        public string texto_cuerpo_correo_nota_credito_cliente { get; set; }
        public string texto_cuerpo_correo_nota_debito_cliente { get; set; }
        public string texto_cuerpo_correo_orden_servicio { get; set; }
        public string texto_cuerpo_correo_pago_proveedor { get; set; }
        public string texto_cuerpo_correo_pedido_cliente { get; set; }
        public string texto_cuerpo_correo_pedido_proveedor { get; set; }
        public string texto_cuerpo_correo_recepcion_proveedor { get; set; }
        public string texto_cuerpo_correo_requisicion { get; set; }
        public string texto_cuerpo_correo_retencion_proveedor { get; set; }
        public string texto_cuerpo_correo_solicitud_compra { get; set; }
        public string texto_cuerpo_correo_transferencia_entre_bodega { get; set; }
        public string texto_cuerpo_correo_vencimiento_factura_cliente { get; set; }
        public bool indicador_notificar_pedido_cliente_aprobacion { get; set; }
        public bool indicador_notificar_pedido_proveedor_aprobacion { get; set; }
        public string texto_cuerpo_correo_pedido_cliente_aprobacion { get; set; }
        public string texto_cuerpo_correo_pedido_proveedor_aprobacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contacto> contacto { get; set; }
    }
}
