//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_proyeccion_kid
    {
        public int id_proyeccion_kid { get; set; }
        public Nullable<decimal> kid { get; set; }
        public byte[] producto_material { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> stock { get; set; }
    }
}
