//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_reporte_asiento
    {
        public int id_tmp_reporte_asiento { get; set; }
        public Nullable<int> id_reporte_factura_proveedor { get; set; }
        public Nullable<int> id_reporte_factura_proveedor_anticipo { get; set; }
        public Nullable<int> id_reporte_factura_proveedor_liquidacion_anticipo { get; set; }
        public Nullable<int> id_reporte_factura_proveedor_nota_credito { get; set; }
        public Nullable<int> id_reporte_factura_proveedor_nota_debito { get; set; }
        public Nullable<int> id_reporte_factura_proveedor_pago { get; set; }
        public Nullable<int> id_reporte_factura_proveedor_liquidacion_recepcion { get; set; }
        public Nullable<int> id_reporte_factura_proveedor_retencion { get; set; }
        public Nullable<int> id_reporte_formas_pago { get; set; }
    
        public virtual tmp_reporte_factura_proveedor tmp_reporte_factura_proveedor { get; set; }
        public virtual tmp_reporte_factura_proveedor tmp_reporte_factura_proveedor1 { get; set; }
        public virtual tmp_reporte_factura_proveedor tmp_reporte_factura_proveedor2 { get; set; }
        public virtual tmp_reporte_factura_proveedor tmp_reporte_factura_proveedor3 { get; set; }
        public virtual tmp_reporte_factura_proveedor tmp_reporte_factura_proveedor4 { get; set; }
        public virtual tmp_reporte_factura_proveedor tmp_reporte_factura_proveedor5 { get; set; }
        public virtual tmp_reporte_factura_proveedor tmp_reporte_factura_proveedor6 { get; set; }
        public virtual tmp_reporte_factura_proveedor tmp_reporte_factura_proveedor7 { get; set; }
        public virtual tmp_reporte_factura_proveedor tmp_reporte_factura_proveedor8 { get; set; }
    }
}
