//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_pago_anticipo_cliente
    {
        public int id_pago_anticipo_cheque { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string documento { get; set; }
        public Nullable<int> documento_base { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_proceso { get; set; }
        public string numero { get; set; }
        public string proveedor { get; set; }
        public Nullable<decimal> valor { get; set; }
    }
}
