//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_relacion_dependencia
    {
        public int relacion_dependencia { get; set; }
        public string apellido { get; set; }
        public string aplica_convenio { get; set; }
        public Nullable<decimal> aportePersonalIess { get; set; }
        public string cedula { get; set; }
        public Nullable<decimal> contribucion_retenida { get; set; }
        public Nullable<decimal> decimoCuarto { get; set; }
        public Nullable<decimal> decimoTercero { get; set; }
        public Nullable<decimal> deducibleAliementacion { get; set; }
        public Nullable<decimal> deducibleEducacion { get; set; }
        public Nullable<decimal> deducibleSalud { get; set; }
        public Nullable<decimal> deducibleVestimenta { get; set; }
        public Nullable<decimal> deducibleVivienda { get; set; }
        public string direccionCalle { get; set; }
        public string direccionCiudad { get; set; }
        public string direccionNumeroCasa { get; set; }
        public string direccionProvincia { get; set; }
        public string establecimiento { get; set; }
        public Nullable<decimal> fondoReserva { get; set; }
        public string identificacion_discapacidad { get; set; }
        public Nullable<long> meses_trabajados_contribucion_empleador { get; set; }
        public Nullable<long> meses_trabajados_contribucion_otro_empleador { get; set; }
        public Nullable<long> meses_trabajados_vigente_contribucion_empleador { get; set; }
        public Nullable<long> meses_trabajados_vigente_contribucion_otro_empleador { get; set; }
        public string nombre { get; set; }
        public Nullable<long> numeroMesesEmpleado { get; set; }
        public Nullable<long> numeroRetenciones { get; set; }
        public Nullable<decimal> otros_ingresos_relacion_dependencia_no_rentaGravada { get; set; }
        public string pais_residencia { get; set; }
        public string porcentaje_discapacidad { get; set; }
        public string residencia_trabajador { get; set; }
        public Nullable<decimal> sobreSueldo { get; set; }
        public Nullable<decimal> sobresueldo_agravada_contribucion_empleador { get; set; }
        public Nullable<decimal> sueldo_agravada_contribucion_empleador { get; set; }
        public Nullable<decimal> sueldo_agravada_contribucion_otro_empleador { get; set; }
        public Nullable<decimal> sueldoSalario { get; set; }
        public string telefono { get; set; }
        public string tipo_identificacion { get; set; }
        public string tipo_identificacion_discapacidad { get; set; }
        public string tipo_trabajador_discapacidad { get; set; }
        public Nullable<decimal> utilidades { get; set; }
        public Nullable<decimal> valor_jornada_reducida { get; set; }
        public Nullable<decimal> valorRetenido { get; set; }
        public Nullable<decimal> deducibleTurismo { get; set; }
    }
}
