//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_reporte_contrato_vencido
    {
        public int id_contrato_venta { get; set; }
        public Nullable<long> cuotas_a_facturar { get; set; }
        public Nullable<long> cuotas_facturadas { get; set; }
        public Nullable<long> cuotas_por_facturar { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public string nombre_fiscal { get; set; }
        public string numero { get; set; }
        public string subempresa_nombre { get; set; }
        public Nullable<int> total_cuotas { get; set; }
        public Nullable<decimal> total_monto { get; set; }
        public Nullable<decimal> valor_a_facturar { get; set; }
        public Nullable<decimal> valor_facturado { get; set; }
        public Nullable<decimal> valor_por_facturar { get; set; }
    }
}
