//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_reporte_cobros
    {
        public int id_reporte_cobros { get; set; }
        public string asiento { get; set; }
        public string factura { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fecha_contabilizacion { get; set; }
        public Nullable<int> identificador_cobro_anticipo { get; set; }
        public string numero { get; set; }
        public Nullable<decimal> valor { get; set; }
    }
}
