//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public turno()
        {
            this.detalle_plan_personalizado_horario_empleado = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado1 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado2 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado3 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado4 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado5 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado6 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado7 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado8 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado9 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado10 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado11 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado12 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado13 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado14 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado15 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado16 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado17 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado18 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado19 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado20 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado21 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado22 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado23 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado24 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado25 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado26 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado27 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado28 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado29 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.detalle_plan_personalizado_horario_empleado30 = new HashSet<detalle_plan_personalizado_horario_empleado>();
            this.horario_empleado = new HashSet<horario_empleado>();
            this.horario_empleado1 = new HashSet<horario_empleado>();
            this.horario_empleado2 = new HashSet<horario_empleado>();
            this.horario_empleado3 = new HashSet<horario_empleado>();
            this.horario_empleado4 = new HashSet<horario_empleado>();
            this.horario_empleado5 = new HashSet<horario_empleado>();
            this.horario_empleado6 = new HashSet<horario_empleado>();
            this.turno_departamento = new HashSet<turno_departamento>();
        }
    
        public int id_turno { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public System.TimeSpan hora_entrada { get; set; }
        public Nullable<System.TimeSpan> hora_receso_entrada { get; set; }
        public Nullable<System.TimeSpan> hora_receso_salida { get; set; }
        public System.TimeSpan hora_salida { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<bool> indicador_pago_horas_suplementarias { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_plan_personalizado_horario_empleado> detalle_plan_personalizado_horario_empleado30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario_empleado> horario_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario_empleado> horario_empleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario_empleado> horario_empleado2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario_empleado> horario_empleado3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario_empleado> horario_empleado4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario_empleado> horario_empleado5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario_empleado> horario_empleado6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turno_departamento> turno_departamento { get; set; }
    }
}
