//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion_bodega
    {
        public int id_ubicacion_bodega { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string posicionX { get; set; }
        public string posicionY { get; set; }
        public string posicionZ { get; set; }
        public bool predeterminado { get; set; }
        public Nullable<int> id_bodega { get; set; }
    
        public virtual bodega bodega { get; set; }
    }
}
