//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_login()
        {
            this.flt_conductores = new HashSet<flt_conductores>();
            this.flt_despachos = new HashSet<flt_despachos>();
            this.flt_recepcion_factura = new HashSet<flt_recepcion_factura>();
            this.pro_responsables = new HashSet<pro_responsables>();
            this.rrhh_adelantos = new HashSet<rrhh_adelantos>();
            this.rrhh_faltas = new HashSet<rrhh_faltas>();
            this.rrhh_sobretiempo = new HashSet<rrhh_sobretiempo>();
            this.tckt_eventos = new HashSet<tckt_eventos>();
            this.tckt_uploading = new HashSet<tckt_uploading>();
            this.urb_guia_principal = new HashSet<urb_guia_principal>();
            this.user_bitacora = new HashSet<user_bitacora>();
            this.user_permisos = new HashSet<user_permisos>();
            this.vend_ubicaciones = new HashSet<vend_ubicaciones>();
            this.vend_vendedores = new HashSet<vend_vendedores>();
        }
    
        public int ID_USER { get; set; }
        public string USERNAME { get; set; }
        public string PWD { get; set; }
        public string NOMBRE { get; set; }
        public string NOMBRE_2 { get; set; }
        public string APELLIDO { get; set; }
        public string APELLIDO_2 { get; set; }
        public string CEDULA { get; set; }
        public string EMPRESA { get; set; }
        public string EMAIL { get; set; }
        public long ID_DPTO { get; set; }
        public string profile_pic { get; set; }
        public Nullable<bool> ADMIN_PRIV { get; set; }
        public string comentario { get; set; }
        public Nullable<bool> online { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public string ultima_ip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flt_conductores> flt_conductores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flt_despachos> flt_despachos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flt_recepcion_factura> flt_recepcion_factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pro_responsables> pro_responsables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_adelantos> rrhh_adelantos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_faltas> rrhh_faltas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_sobretiempo> rrhh_sobretiempo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tckt_eventos> tckt_eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tckt_uploading> tckt_uploading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urb_guia_principal> urb_guia_principal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_bitacora> user_bitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_permisos> user_permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vend_ubicaciones> vend_ubicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vend_vendedores> vend_vendedores { get; set; }
    }
}
