//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_cuenta_organizacion
    {
        public int id_usuario_cuenta_bancaria_organizacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<int> id_cuenta_bancaria_organizacion { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual cuenta_bancaria_organizacion cuenta_bancaria_organizacion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
