//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_despachos
    {
        public int id_detalle_despacho_cliente { get; set; }
        public string numero_documento { get; set; }
        public int id_producto { get; set; }
        public string codigo_producto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string nombre_atributo1 { get; set; }
        public string nombre_atributo2 { get; set; }
        public string nombre_atributo3 { get; set; }
        public string valor_atributo1 { get; set; }
        public string valor_atributo2 { get; set; }
        public string valor_atributo3 { get; set; }
    }
}
