//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_estado_cuenta_proveedor
    {
        public Nullable<int> id_sucursal { get; set; }
        public string nombre_sucursal { get; set; }
        public int id_empresa { get; set; }
        public string nombre_fiscal { get; set; }
        public string codigo { get; set; }
        public string identificacion { get; set; }
        public string numero_factura { get; set; }
        public System.DateTime fecha_factura { get; set; }
        public Nullable<System.DateTime> fecha_recepcion_factura { get; set; }
        public int id_factura_proveedor { get; set; }
        public string descripcion_factura { get; set; }
        public string descripcion_documento { get; set; }
        public System.DateTime fecha_documento { get; set; }
        public string numero_documento { get; set; }
        public string codigo_documento { get; set; }
        public string nombre_documento { get; set; }
        public int id_cuenta_por_pagar { get; set; }
        public System.DateTime fecha_vence { get; set; }
        public decimal debito { get; set; }
        public decimal credito { get; set; }
        public int id_organizacion { get; set; }
        public Nullable<int> id_tipo_operacion { get; set; }
        public string tipo_operacion { get; set; }
        public string codigo_documento_proceso { get; set; }
        public string asiento_compra { get; set; }
        public string asiento_documento { get; set; }
        public decimal valor_retenido { get; set; }
        public string referencia1 { get; set; }
        public string referencia2 { get; set; }
        public Nullable<decimal> valor_referencia1 { get; set; }
        public Nullable<decimal> valor_referencia2 { get; set; }
        public Nullable<decimal> valor_referencia3 { get; set; }
        public int id_categoria_empresa { get; set; }
        public string nombre_categoria_empresa { get; set; }
        public int documento_base { get; set; }
        public Nullable<int> id_pago { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public string numero_retencion { get; set; }
        public string descripcion_forma_pago { get; set; }
        public string referencia3 { get; set; }
        public string proyecto { get; set; }
        public string descripcionFacturaProveedor { get; set; }
        public Nullable<int> id_empresa_manager { get; set; }
    }
}
