//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class val_vales_principal
    {
        public int id_vale { get; set; }
        public string codigo_cobro { get; set; }
        public float valor_cobro { get; set; }
        public System.DateTime fecha_reportado { get; set; }
        public string empresa { get; set; }
        public bool anulado { get; set; }
    
        public virtual clnt_cobro_validado clnt_cobro_validado { get; set; }
        public virtual clnt_cobro_validado clnt_cobro_validado1 { get; set; }
    }
}
