//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class variable_calidad_registro_peso
    {
        public int id_variable_calidad_registro_peso { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string observacion { get; set; }
        public Nullable<decimal> valor_nir { get; set; }
        public string valor_unico { get; set; }
        public int id_variable_calidad_producto { get; set; }
        public int id_registro_peso { get; set; }
    
        public virtual registro_peso registro_peso { get; set; }
        public virtual variable_calidad_producto variable_calidad_producto { get; set; }
    }
}
