//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedores
    {
        public string empresa { get; set; }
        public string sucursal { get; set; }
        public int id_vendedor { get; set; }
        public string nombre { get; set; }
        public string username { get; set; }
    }
}
