//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class version_comision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public version_comision()
        {
            this.comision = new HashSet<comision>();
        }
    
        public int id_version_comision { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string nombre { get; set; }
        public bool predeterminado { get; set; }
        public Nullable<int> id_tarjeta_credito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comision> comision { get; set; }
        public virtual tarjeta_credito tarjeta_credito { get; set; }
    }
}
